// Moved to `@tj/slides` (ADR 0030 item 4): the word search recipe needs the grid. Re-exported
// here so every `./word-search` import in the editor keeps resolving.
export {
  buildWordSearch,
  clampSize,
  directionVectors,
  findWord,
  generateWordSearch,
  type NormalisedWords,
  normaliseWordList,
  normaliseWords,
  rejectedMessage,
  solutionMask,
  textToWords,
  unfittableMessage,
  WORD_SEARCH_DEFAULT_SIZE,
  WORD_SEARCH_MAX_SIZE,
  WORD_SEARCH_MIN_SIZE,
  type WordSearchDirections,
  type WordSearchGrid,
  type WordSearchOccurrence,
  type WordSearchOptions,
  type WordSearchPlacement,
  type WordSearchProblems,
  type WordSearchResult,
  type WordSearchSpec,
  wordOccurrences,
  wordSearchLead,
  wordSearchProblems,
  wordsToText,
} from "@tj/slides/worksheet";
