import type { IconElement } from "@tj/domain/documents";
import {
  AlarmClock,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom,
  Award,
  Backpack,
  Bell,
  Bird,
  Book,
  BookOpen,
  Brain,
  Bug,
  Calculator,
  Camera,
  Castle,
  Cat,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSun,
  Compass,
  Divide,
  Dna,
  Dog,
  Droplet,
  Droplets,
  Ear,
  Earth,
  Equal,
  Eraser,
  Eye,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Frown,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  Heart,
  HeartPulse,
  Highlighter,
  House,
  Infinity as InfinityIcon,
  Info,
  Key,
  Leaf,
  Library,
  Lightbulb,
  List,
  ListChecks,
  ListOrdered,
  Lock,
  type LucideIcon,
  Magnet,
  Map as MapIcon,
  MapPin,
  Megaphone,
  Mic,
  Microscope,
  Minus,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Paintbrush,
  Palette,
  Pause,
  Pencil,
  Percent,
  Plane,
  Play,
  Plus,
  Puzzle,
  Quote,
  Rabbit,
  Rainbow,
  Recycle,
  Rocket,
  Ruler,
  Scissors,
  Search,
  Shapes,
  Ship,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Sunrise,
  Table,
  Target,
  Telescope,
  TestTubes,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TreePine,
  Trees,
  Triangle,
  TriangleAlert,
  Trophy,
  Umbrella,
  User,
  Users,
  WavesHorizontal,
  Wind,
  X,
  Zap,
} from "lucide-react";
import { clamp, type ElementViewProps } from "./kit";

/**
 * A curated classroom set: 124 icons a lesson actually reaches for, every one a named
 * static import so it resolves synchronously in `capture` and `thumb` and tree-shakes
 * out of the bundle when it is not used.
 *
 * Deliberately NOT `lucide-react/dynamic`: that manifest is 2057 lazy imports (122 KB of
 * source) and importing it anywhere puts it in the chunk every slide renders. A name
 * outside this set — from an imported lesson written against a later picker — falls back
 * to a neutral placeholder glyph, in every mode, rather than pulling the manifest in.
 */
export const ICONS: Record<string, LucideIcon> = {
  /* Reading, writing and the classroom */
  apple: Apple,
  backpack: Backpack,
  bell: Bell,
  book: Book,
  "book-open": BookOpen,
  eraser: Eraser,
  "graduation-cap": GraduationCap,
  highlighter: Highlighter,
  library: Library,
  "list-checks": ListChecks,
  megaphone: Megaphone,
  "notebook-pen": NotebookPen,
  pencil: Pencil,
  quote: Quote,

  /* Maths */
  calculator: Calculator,
  divide: Divide,
  equal: Equal,
  infinity: InfinityIcon,
  "list-ordered": ListOrdered,
  minus: Minus,
  percent: Percent,
  plus: Plus,
  ruler: Ruler,
  shapes: Shapes,
  square: Square,
  table: Table,
  triangle: Triangle,

  /* Science */
  atom: Atom,
  dna: Dna,
  droplet: Droplet,
  droplets: Droplets,
  flame: Flame,
  "flask-conical": FlaskConical,
  "heart-pulse": HeartPulse,
  leaf: Leaf,
  magnet: Magnet,
  microscope: Microscope,
  sprout: Sprout,
  telescope: Telescope,
  "test-tubes": TestTubes,
  thermometer: Thermometer,

  /* Weather, time and the natural world */
  "alarm-clock": AlarmClock,
  bird: Bird,
  bug: Bug,
  cat: Cat,
  clock: Clock,
  cloud: Cloud,
  "cloud-lightning": CloudLightning,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  dog: Dog,
  earth: Earth,
  fish: Fish,
  globe: Globe,
  moon: Moon,
  mountain: Mountain,
  rabbit: Rabbit,
  rainbow: Rainbow,
  snowflake: Snowflake,
  sun: Sun,
  sunrise: Sunrise,
  timer: Timer,
  "tree-pine": TreePine,
  trees: Trees,
  umbrella: Umbrella,
  "waves-horizontal": WavesHorizontal,
  wind: Wind,

  /* Geography and history */
  castle: Castle,
  compass: Compass,
  flag: Flag,
  house: House,
  map: MapIcon,
  "map-pin": MapPin,
  plane: Plane,
  ship: Ship,

  /* People, PSHE and behaviour */
  ear: Ear,
  eye: Eye,
  frown: Frown,
  hand: Hand,
  handshake: Handshake,
  heart: Heart,
  smile: Smile,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  user: User,
  users: Users,

  /* Arts, music and play */
  award: Award,
  camera: Camera,
  mic: Mic,
  music: Music,
  paintbrush: Paintbrush,
  palette: Palette,
  puzzle: Puzzle,
  scissors: Scissors,
  trophy: Trophy,

  /* Signals and pointers */
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  brain: Brain,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-question-mark": CircleQuestionMark,
  "circle-x": CircleX,
  info: Info,
  key: Key,
  lightbulb: Lightbulb,
  list: List,
  lock: Lock,
  pause: Pause,
  play: Play,
  recycle: Recycle,
  rocket: Rocket,
  search: Search,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  "triangle-alert": TriangleAlert,
  x: X,
  zap: Zap,
};

/** Icon names offered in the insert picker, grouped by subject in `ICONS` order. */
export const ICON_NAMES = Object.keys(ICONS);

/** What an unknown icon name renders as. */
const FALLBACK_ICON: LucideIcon = Square;

export function IconView({ element, theme }: ElementViewProps<IconElement>) {
  const size = Math.max(8, Math.min(element.w, element.h));
  // absoluteStrokeWidth keeps the stroke at this many points whatever the icon's size,
  // so a 140pt icon does not turn into a slab.
  const strokeWidth = element.strokeWidth ?? clamp(size / 28, 2, 6);
  const color = element.color ?? theme.colors.accent;
  const Glyph = ICONS[element.icon] ?? FALLBACK_ICON;

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color,
      }}
    >
      <Glyph size={size} strokeWidth={strokeWidth} absoluteStrokeWidth aria-hidden />
    </div>
  );
}
