import catalogue from "./catalogue.json";
import type { Stage } from "./index";

/*
 * The pupil objective line's word limit, from the writer templates' measured capacities
 * (`catalogue.json`, regenerated by `scripts/catalogue.ts` and equal to lab/ab's; the parity test
 * is `lab-tables.test.ts`). Server-side only: `@tj/slides/templates/pupil-words`, never re-exported
 * from a browser entry (`bundle.test.ts`).
 */
type Catalogue = {
  templates: {
    id: string;
    capacity: Record<string, { variants: { label: string; maxCharsPerItem: number }[] }>;
  }[];
};

const KEY: Record<Stage, string> = {
  ks1: "KS1",
  ks2: "KS2",
  ks3: "KS3-5",
  ks4: "KS3-5",
  ks5: "KS3-5",
};

/**
 * The objectives slide's measured room for `n` objectives at `stage`, in words: maxCharsPerItem ÷ 6
 * (at least 6, as the lab's `pupilWordLimit`). Throws when the catalogue has no such entry; the lab
 * fell back to fixed 8/10/12 words, which the port does not carry.
 */
export function pupilWordLimit(stage: Stage, n: number): number {
  const key = KEY[stage];
  const o = (catalogue as Catalogue).templates.find((t) => t.id === "objectives");
  const v = o?.capacity[key]?.variants.find((x) => x.label === `${n} objectives`);
  if (!v?.maxCharsPerItem)
    throw new Error(`no objectives capacity for ${n} objectives at ${key} in catalogue.json`);
  return Math.max(6, Math.floor(v.maxCharsPerItem / 6));
}
