// Generated from the pinned writer's diagram contract (the drawer call's code-held text at the
// evidence pin); do not edit. Wording changes go through the prompt-engineer agent.
import { diagramSpec } from "./writer-prompts.gen";

export const DIAGRAM_CONTRACT =
  "- diagram: the drawing itself, as a diagram spec of one kind; never shown as text. Templates come first: particles (arrangement of particles in solids, liquids and gases, diffusion, dissolving), hydrograph (a storm hydrograph), timeline (dated events in order), layers (a layered structure or cross-section), cycle (a cycle of three to five steps), river (a V-shaped valley, or a meander across or from above), bar-model and number-line. A template's slots are its words and values only; code draws it. Use a template whenever it shows the idea, and the free kinds (line-graph, labelled-diagram, flow, table) only when none does. Its text is labels, not sentences: a label, annotation, interval, series name, particle caption or table header is one to three words; an axis label is a few words with its unit; a flow step is a short phrase and a flow arrow one or two words; a table cell is a short phrase; the title is one short line and the alt one sentence. A field with nothing to say is left out, never empty.\n  - line-graph: an annotation marks one point of one series, at that point's own x and y (on the series' own axis), and its label names that series' feature (\"Peak rainfall\" at the tallest rainfall bar, \"Peak discharge\" at the top of the discharge line). An interval's y is in the left axis's units, below both curves' peaks. A lag time is an interval from the rainfall peak's x to the discharge peak's x.\n  - labelled-diagram: shapes on a canvas 100 high (100 or 160 wide). Each label's point is inside or on the shape it names; a label is 1 to 3 words, one per shape, at most 6. Particle boxes are one per state, the caption the state's name; a label on a particle box says something the caption does not (\"fixed rows\", never the state's name again).";
export const DIAGRAM_CONTRACT_SHA256 =
  "c684d644e2cde9d1987ab579edf5d46ff926ae22a0ceae6f0a978e6a90f61739";

/** The drawer fallback's system text, exactly as the pinned writer sent it (part d calls it). */
export const writerDrawerSystem = `${diagramSpec.trim()}\n\n${DIAGRAM_CONTRACT}`;
