import { readFileSync, writeFileSync } from "node:fs";
import { chromium } from "@playwright/test";

/**
 * Regenerates `packages/slides/src/font-metrics.generated.ts` (TEACH-70): measures every theme
 * font's printable ASCII advances in Chromium. Run from `apps/web`: `bun scripts/gen-font-metrics.ts`.
 */
const REPO = new URL("../../../", import.meta.url).pathname;
const ROOT = `${REPO}node_modules/.bun`;
const FONTS: Record<string, string> = {
  lexend: "lexend",
  gabarito: "gabarito",
  figtree: "figtree",
  sourceSerif: "source-serif-4",
  schibsted: "schibsted-grotesk",
  literata: "literata",
  publicSans: "public-sans",
  bricolage: "bricolage-grotesque",
  instrumentSans: "instrument-sans",
  atkinson: "atkinson-hyperlegible-next",
};
const WEIGHTS = [400, 600, 700];
const CHARS = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join("");

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent("<html><body></body></html>");
const out: Record<string, Record<number, number[]>> = {};
for (const [key, pkg] of Object.entries(FONTS)) {
  const file = `${ROOT}/@fontsource-variable+${pkg}@5.3.0/node_modules/@fontsource-variable/${pkg}/files/${pkg}-latin-wght-normal.woff2`;
  const b64 = readFileSync(file).toString("base64");
  out[key] = await page.evaluate(
    async ({ key, b64, WEIGHTS, CHARS }) => {
      const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
      const face = new FontFace(`m-${key}`, bytes.buffer, { weight: "100 900" });
      await face.load();
      document.fonts.add(face);
      const ctx = document.createElement("canvas").getContext("2d");
      if (!ctx) throw new Error("no canvas");
      const res: Record<number, number[]> = {};
      for (const w of WEIGHTS) {
        ctx.font = `${w} 1000px "m-${key}"`;
        res[w] = [...CHARS].map((c) => Math.round(ctx.measureText(c).width));
      }
      return res;
    },
    { key, b64, WEIGHTS, CHARS },
  );
}
await browser.close();

const lines = Object.entries(out).map(
  ([key, byWeight]) =>
    `  ${key}: {\n${Object.entries(byWeight)
      .map(([w, arr]) => `    ${w}: [${arr.join(", ")}],`)
      .join("\n")}\n  },`,
);
writeFileSync(
  `${REPO}packages/slides/src/font-metrics.generated.ts`,
  `/*
 * GENERATED by \`apps/web/scripts/gen-font-metrics.ts\`, measuring the theme fonts (the \`@fontsource-variable/*\` latin files the editor
 * loads) in Chromium: the advance width of every printable ASCII character, U+0020 to U+007E, in
 * thousandths of an em, at weights 400, 600 and 700. Do not edit by hand.
 */
import type { FontKey } from "./fonts";

export const ADVANCES: Partial<Record<FontKey, Record<400 | 600 | 700, readonly number[]>>> = {
${lines.join("\n")}
};
`,
);
console.log("ok", Object.keys(out).length);
