/**
 * The single environment contract for Teaching Journey (TEACH-26, ADR 0015 / 0010).
 *
 * Every variable any app, package, script or CI job reads is declared here **once**, with where
 * it lives (local `.env` files, Railway, Vercel, CI) and who sets it. Everything else is derived:
 *
 *   - `docs/env.md`, every `.env.example` and `.gitleaks.toml` are GENERATED by
 *     `bun run env:generate` (`--check` in CI fails when they drift);
 *   - `bun run doctor` validates the local `.env` files against it;
 *   - `bun run env:check` compares the variable NAMES on Railway / Vercel against it;
 *   - `apps/<app>/src/env.contract.test.ts` assert that each app's Zod schema and this file agree;
 *   - `scripts/env-contract.test.ts` asserts `turbo.json#env` lists only declared names.
 *
 * This file has no dependencies (it is imported by root scripts and by every app's tests) and
 * contains NO VALUES that are secret: `local` holds the synthetic docker-compose defaults only.
 * Names are the unit of truth; values live in the provider (Railway / Vercel) or in a gitignored
 * `.env`. Edit this file, then run `bun run env:generate`.
 */

/** Who reads the variable. `compose` = docker compose + the root scripts (root `.env`). */
export type EnvService = "api" | "worker" | "web" | "ci" | "compose";

/** `secret` values are never printed, never in git and get a gitleaks rule; `config` is public. */
export type EnvScope = "secret" | "config";

/** Which Railway environments carry the variable (`n/a` = not a Railway variable). */
export type RailwayTarget = "prod" | "pr" | "both" | "n/a";

/** Which Vercel environments carry the variable (`n/a` = not a Vercel variable). */
export type VercelTarget = "prod" | "preview" | "both" | "n/a";

/**
 * How the provider value comes into being:
 * - `reference` — a Railway reference/template (`${{postgres.POSTGRES_PASSWORD}}`), set by
 *   `infra/railway/provision.sh`;
 * - `template` — a plain config value seeded by `provision.sh` / `vercel env add`;
 * - `generated` — random, created by `bun run setup` (local) or `provision.sh` (Railway);
 * - `manual` — a human pastes it (OAuth credentials, tokens, domains).
 */
export type EnvSetBy = "reference" | "manual" | "template" | "generated";

/** The `.env.example` files `bun run env:generate` writes. */
export type EnvFile = "root" | "api" | "worker" | "web" | "db" | "jobs";

/** What `bun run doctor` validates when a value is present locally. */
export type EnvFormat =
  | "url"
  | "postgres-url"
  | "port"
  | "int"
  | "enum"
  | "origin-list"
  | "origin-pattern-list"
  | "string";

/** Where a variable appears in a `.env.example`, optionally commented-out or with another value. */
export type EnvPlacement =
  | EnvFile
  | {
      file: EnvFile;
      /** Emit as `# NAME=` (documented, opt-in). Defaults to `local === null`. */
      commented?: boolean;
      /** Per-file value when it differs from `local` (e.g. the worker's `PORT`). */
      value?: string;
    };

export interface EnvVar {
  readonly name: string;
  readonly services: readonly EnvService[];
  readonly scope: EnvScope;
  /**
   * Value written to `.env.example` for the local compose stack, or `null` when the variable is
   * optional / not needed locally (then it is emitted commented-out where `files` lists it).
   */
  readonly local: string | null;
  readonly railway: RailwayTarget;
  readonly vercel: VercelTarget;
  readonly setBy?: EnvSetBy;
  /** One or two sentences; becomes the comment above the key in `.env.example` and the docs. */
  readonly description: string;
  /** `.env.example` files that carry the key. Empty = provider/CI-only or shell-only. */
  readonly files?: readonly EnvPlacement[];
  /** Validation `doctor` applies to a present local value (default: none). */
  readonly format?: EnvFormat;
  /** Allowed values when `format === "enum"`. */
  readonly values?: readonly string[];
  /**
   * Read outside the service's boot-time Zod schema (tests, `vite.config.ts`, build scripts,
   * platform-injected) — the schema-parity tests do not expect it in `EnvSchema`.
   */
  readonly runtimeOnly?: boolean;
  /**
   * Non-secret value (or Railway reference) that `infra/railway/provision.sh` seeds on the api /
   * worker services via `scripts/railway-vars.ts`. Secrets never have one.
   */
  readonly railwayValue?: string;
}

const PG_LOCAL = "postgres://postgres:postgres@localhost:5432/teaching_journey";
const PG_LOCAL_TEST = "postgres://postgres:postgres@localhost:5432/teaching_journey_test";
// Keep these dependency-free: packages/ai/src/env-contract-defaults.test.ts asserts they match
// @tj/ai's exported defaults.
const AI_DEFAULT_REGION = "us-east-1";
const AI_DEFAULT_MODEL_IDS = {
  frontier: "us.anthropic.claude-opus-5",
  standard: "us.anthropic.claude-sonnet-5",
  small: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
} as const;
/** Railway reference syntax (`${"{{"}service.VAR}}`), resolved by Railway, not a JS template. */
const RAILWAY_DB_REF = [
  "postgres://$",
  "{{postgres.POSTGRES_USER}}:$",
  "{{postgres.POSTGRES_PASSWORD}}@$",
  "{{postgres.RAILWAY_PRIVATE_DOMAIN}}:5432/$",
  "{{postgres.POSTGRES_DB}}",
].join("");

export const LOG_LEVELS = ["fatal", "error", "warn", "info", "debug", "trace", "silent"] as const;
export const NODE_ENVS = ["development", "test", "production"] as const;

/**
 * The contract. Order is the order of `docs/env.md` and of every `.env.example`; keep related
 * variables together (database, runtime, auth, storage, events, web, tooling).
 */
const CONTRACT = [
  // --- database -----------------------------------------------------------------------------
  {
    name: "TJ_PG_PORT",
    services: ["compose"],
    scope: "config",
    local: "5432",
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "port",
    files: ["root"],
    description:
      "Host port docker compose publishes Postgres on. The single knob for a port conflict: the root scripts derive DATABASE_URL / TEST_DATABASE_URL from it when those are unset. Shell wins over the file (`TJ_PG_PORT=5433 bun run db:up`).",
  },
  {
    name: "DATABASE_URL",
    services: ["api", "worker", "compose", "ci"],
    scope: "secret",
    local: PG_LOCAL,
    railway: "both",
    vercel: "n/a",
    setBy: "reference",
    format: "postgres-url",
    files: [{ file: "root", commented: true }, "api", "worker", "db"],
    railwayValue: RAILWAY_DB_REF,
    description:
      "Postgres connection of the app database (pg-boss installs its own `pgboss` schema in it). Locally the compose database; keep the port in sync with TJ_PG_PORT. On Railway a reference to the `postgres` service over the private network. Contains the password: treat as a secret.",
  },
  {
    name: "TEST_DATABASE_URL",
    services: ["api", "worker", "web", "compose", "ci"],
    scope: "secret",
    local: PG_LOCAL_TEST,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "postgres-url",
    runtimeOnly: true,
    files: [{ file: "root", commented: true }, "api", "db", "jobs"],
    description:
      "Database the test suites and Playwright use (`@tj/db/testing`, docs/testing.md). Tests TRUNCATE tables here, so it must never equal DATABASE_URL. Never read by a running server.",
  },

  // --- runtime (api + worker) ----------------------------------------------------------------
  {
    name: "NODE_ENV",
    services: ["api", "worker"],
    scope: "config",
    local: "development",
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "enum",
    values: NODE_ENVS,
    files: ["api", "worker"],
    railwayValue: "production",
    description:
      "development | test | production. `development` switches on pino-pretty; `production` refuses ENABLE_TEST_ROUTES and ALLOW_WORKSPACE_HEADER_SHIM.",
  },
  {
    name: "PORT",
    services: ["api", "worker"],
    scope: "config",
    local: "3001",
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "port",
    files: ["api", { file: "worker", value: "3002" }],
    description:
      "TCP port of Bun.serve: api 3001 (HTTP + SSE), worker 3002 (`/health` only). Railway routes the public domain to the api's PORT; the worker has no public domain.",
  },
  {
    name: "LOG_LEVEL",
    services: ["api", "worker"],
    scope: "config",
    local: "info",
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "enum",
    values: LOG_LEVELS,
    files: ["api", "worker"],
    railwayValue: "info",
    description: "pino level: fatal | error | warn | info | debug | trace | silent.",
  },
  {
    name: "WORKER_CONCURRENCY",
    services: ["worker"],
    scope: "config",
    local: "4",
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["worker"],
    railwayValue: "4",
    description: "Jobs processed concurrently per queue in one worker process (1-64).",
  },

  // --- api: CORS + auth (ADR 0008) --------------------------------------------------------------
  {
    name: "WEB_ORIGIN",
    services: ["api"],
    scope: "config",
    local: "http://localhost:5173",
    railway: "both",
    vercel: "n/a",
    setBy: "manual",
    format: "origin-list",
    files: ["api"],
    railwayValue: "https://teaching-journey-web.vercel.app",
    description:
      "Comma-separated exact browser origins allowed by CORS (credentials on) and trusted by better-auth. Locally the Vite dev server; on Railway the Vercel production origin (`https://teaching-journey-web.vercel.app`, later `https://app.<domain>`).",
  },
  {
    name: "WEB_ORIGIN_PATTERNS",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    railwayValue: "https://teaching-journey-web-*-omerbresinskis-projects.vercel.app",
    format: "origin-pattern-list",
    files: ["api"],
    description:
      "Optional comma-separated origin GLOBS for per-deployment Vercel preview URLs (`*` = one DNS label, no path), e.g. `https://teaching-journey-web-*-omerbresinskis-projects.vercel.app`. Set on Railway production so PR environments (copies of production) inherit it; the api ignores it when no preview origin matches. Unset locally.",
  },
  {
    name: "BETTER_AUTH_SECRET",
    services: ["api"],
    scope: "secret",
    local: null,
    railway: "both",
    vercel: "n/a",
    setBy: "generated",
    format: "string",
    files: ["api"],
    description:
      "Signs session cookies and magic-link tokens; REQUIRED, at least 32 characters. `bun run setup` generates it into apps/api/.env (crypto.randomBytes(32), base64url) and never prints it; `infra/railway/provision.sh` does the same on Railway (`openssl rand -base64 32 | railway variable set BETTER_AUTH_SECRET --stdin`). Rotating it signs everyone out.",
  },
  {
    name: "BETTER_AUTH_URL",
    services: ["api"],
    scope: "config",
    local: "http://localhost:3001",
    railway: "both",
    vercel: "n/a",
    setBy: "reference",
    format: "url",
    files: ["api"],
    // biome-ignore lint/suspicious/noTemplateCurlyInString: Railway reference syntax
    railwayValue: "https://${{RAILWAY_PUBLIC_DOMAIN}}",
    description:
      "Public origin of this API; magic links are `<BETTER_AUTH_URL>/auth/magic-link/verify?...`. On Railway the reference `https://$" +
      "{{RAILWAY_PUBLIC_DOMAIN}}` resolves per environment (PR envs included).",
  },
  {
    name: "COOKIE_DOMAIN",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    format: "string",
    files: ["api"],
    description:
      "Parent domain of the session cookie (`.<domain>`) so app.<domain> and api.<domain> share it. Unset locally (the Vite proxy makes web and api same-origin) and until custom domains exist (ADR 0010).",
  },
  {
    name: "COOKIE_SAMESITE",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "enum",
    values: ["lax", "none", "strict"],
    files: ["api"],
    railwayValue: "none",
    description:
      "lax (default) | none | strict. `none` makes the cookie `SameSite=None; Secure` (Secure forced whatever NODE_ENV, boot warning) for web and api on unrelated origins — Vercel preview <-> Railway PR api, and **production today** (`*.vercel.app` <-> `*.up.railway.app`, set 2026-09-04). Once `app.<d>`/`api.<d>` exist, switch production to `lax` + COOKIE_DOMAIN (ADR 0008).",
  },
  {
    name: "MAIL_PROVIDER",
    services: ["api"],
    scope: "config",
    local: "console",
    railway: "both",
    vercel: "n/a",
    setBy: "template",
    format: "enum",
    values: ["console"],
    files: ["api"],
    railwayValue: "console",
    description:
      "Magic-link delivery. Only `console` exists until TEACH-29 configures a real provider. In production it is refused unless ALLOW_CONSOLE_MAIL_IN_PRODUCTION=1; each link is printed in the api log at warn level.",
  },
  {
    name: "ALLOW_CONSOLE_MAIL_IN_PRODUCTION",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "both",
    vercel: "n/a",
    setBy: "manual",
    format: "enum",
    values: ["1"],
    files: ["api"],
    railwayValue: "1",
    description:
      "Acknowledges that with MAIL_PROVIDER=console in production every magic-link URL is printed to the api log. Required for console mail in production; delete when TEACH-29 lands.",
  },
  {
    name: "GOOGLE_CLIENT_ID",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    files: ["api"],
    description:
      "OAuth client id (F17). Unset disables Google sign-in (the api logs `Google sign-in disabled`).",
  },
  {
    name: "GOOGLE_CLIENT_SECRET",
    services: ["api"],
    scope: "secret",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    files: ["api"],
    description: "OAuth client secret paired with GOOGLE_CLIENT_ID (F17).",
  },
  {
    name: "MICROSOFT_CLIENT_ID",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    files: ["api"],
    description: "OAuth application (client) id (F17). Unset disables Microsoft sign-in.",
  },
  {
    name: "MICROSOFT_CLIENT_SECRET",
    services: ["api"],
    scope: "secret",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    files: ["api"],
    description: "OAuth client secret paired with MICROSOFT_CLIENT_ID (F17).",
  },
  {
    name: "ENABLE_TEST_ROUTES",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    format: "enum",
    values: ["1"],
    files: ["api"],
    description:
      '"1" mounts the test-only routes (`/__test/*`, TEACH-22) when NODE_ENV=test. Refused at boot when NODE_ENV=production; never set it on Railway.',
  },
  {
    name: "ALLOW_WORKSPACE_HEADER_SHIM",
    services: ["api"],
    scope: "config",
    local: "1",
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "enum",
    values: ["1"],
    files: ["api"],
    description:
      "Development/test only: lets x-tj-workspace-id select a Workspace without a session. Refused at boot when NODE_ENV=production; never set it on Railway.",
  },

  // --- storage (ADR 0011) ------------------------------------------------------------------------
  {
    name: "BLOB_READ_WRITE_TOKEN",
    services: ["api", "worker", "ci"],
    scope: "secret",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    runtimeOnly: true,
    files: ["api", "worker"],
    description:
      'Vercel Blob read-write token for the private store `teaching-journey` (`store_Ii6wcxuuLOvPP4ou`, `fra1`; infra/README.md "Vercel Blob (files)"). When set (non-blank) `@tj/storage` picks `VercelBlobStorage`; otherwise the local-disk adapter under `.data/`. Set on Railway api + worker since 2026-09-04 (TEACH-37); never on Vercel — the SPA does not read it. Optional in CI to run the Blob contract tests.',
  },
  {
    name: "STORAGE_PUBLIC_BASE_URL",
    services: ["api", "worker"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    format: "url",
    runtimeOnly: true,
    files: ["api", "worker"],
    description:
      "Local-disk adapter only: base URL returned by `getSignedUrl` instead of `file://` paths.",
  },
  {
    name: "STORAGE_ROOT",
    services: ["api", "worker"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    format: "string",
    runtimeOnly: true,
    files: ["api", "worker"],
    description:
      "Local-disk adapter only: directory that holds stored objects. Defaults to `.data/storage` (gitignored) when unset.",
  },
  {
    name: "STORAGE_PUBLIC_PREFIXES",
    services: ["api", "worker"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    format: "string",
    runtimeOnly: true,
    files: ["api", "worker"],
    description:
      'Comma-separated key prefixes treated as public by `@tj/storage` (served by URL instead of the `GET /files/:key` proxy). Empty means everything is private. Leave unset on Railway: the production store `teaching-journey` is a **private** store and rejects `access: "public"` uploads.',
  },

  // --- AI provider (ADR 0018) ---------------------------------------------------------------------
  {
    name: "AWS_BEARER_TOKEN_BEDROCK",
    services: ["api", "worker"],
    scope: "secret",
    local: null,
    railway: "prod",
    vercel: "n/a",
    setBy: "manual",
    format: "string",
    files: ["api", "worker"],
    description:
      "Amazon Bedrock API key (bearer). Required in production; when unset in development/test `@tj/ai` is `unconfigured` and AI jobs/routes fail fast. Never set on Vercel (ADR 0018).",
  },
  {
    name: "AWS_REGION",
    services: ["api", "worker"],
    scope: "config",
    local: AI_DEFAULT_REGION,
    railway: "prod",
    vercel: "n/a",
    setBy: "template",
    format: "string",
    files: ["api", "worker"],
    railwayValue: AI_DEFAULT_REGION,
    description:
      "Amazon Bedrock region. `us-east-1` is the data-residency deviation recorded in ADR 0016 §5; production uses this value (ADR 0018).",
  },
  {
    name: "AI_MODEL_FRONTIER",
    services: ["api", "worker"],
    scope: "config",
    local: AI_DEFAULT_MODEL_IDS.frontier,
    railway: "prod",
    vercel: "n/a",
    setBy: "template",
    format: "string",
    files: ["api", "worker"],
    railwayValue: AI_DEFAULT_MODEL_IDS.frontier,
    description:
      "Bedrock model ID for the F13 §7 frontier class: planning, adaptation and coherence.",
  },
  {
    name: "AI_MODEL_STANDARD",
    services: ["api", "worker"],
    scope: "config",
    local: AI_DEFAULT_MODEL_IDS.standard,
    railway: "prod",
    vercel: "n/a",
    setBy: "template",
    format: "string",
    files: ["api", "worker"],
    railwayValue: AI_DEFAULT_MODEL_IDS.standard,
    description:
      "Bedrock model ID for the F13 §7 standard class: plan, notes and slide outline generation.",
  },
  {
    name: "AI_MODEL_SMALL",
    services: ["api", "worker"],
    scope: "config",
    local: AI_DEFAULT_MODEL_IDS.small,
    railway: "prod",
    vercel: "n/a",
    setBy: "template",
    format: "string",
    files: ["api", "worker"],
    railwayValue: AI_DEFAULT_MODEL_IDS.small,
    description:
      "Bedrock model ID for the F13 §7 small class: items, glossary, variants and summaries.",
  },

  // --- api: SSE knobs (ADR 0012, apps/api/src/events/config.ts) ----------------------------------
  {
    name: "EVENTS_MAX_STREAMS_PER_WORKSPACE",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description: "Concurrent SSE streams per Workspace before `429 rate_limited` (default 20).",
  },
  {
    name: "EVENTS_REPLAY_LIMIT",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description: "Most `job_events` rows replayed when a stream opens (default 500, max 5000).",
  },
  {
    name: "EVENTS_HEARTBEAT_MS",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description: "Interval of the `: ping` SSE comment that keeps proxies awake (default 15000).",
  },
  {
    name: "EVENTS_POLL_MS",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description:
      "Poll interval while the LISTEN connection is down — degraded mode (default 1000).",
  },

  // --- api: AI request rate-limit knobs (apps/api/src/rate-limit.ts) --------------------------------
  {
    name: "AI_RATE_LIMIT_PER_WORKSPACE",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description:
      "Model-call requests per Workspace per window on the AI routes (`/jobs/ai-ping`, `/me/greeting`) before `429 rate_limited` (default 10).",
  },
  {
    name: "AI_RATE_LIMIT_WINDOW_S",
    services: ["api"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "int",
    files: ["api"],
    description: "Window length in seconds for `AI_RATE_LIMIT_PER_WORKSPACE` (default 60).",
  },

  // --- web (Vite / Vercel, ADR 0004 / 0010) ---------------------------------------------------------
  {
    name: "VITE_API_URL",
    services: ["web"],
    scope: "config",
    local: "/api",
    railway: "n/a",
    vercel: "prod",
    setBy: "manual",
    format: "string",
    files: ["web"],
    description:
      "Base URL the browser uses for the API. Locally `/api`: the Vite dev server proxies `/api/*` to the api and strips the prefix so cookies stay same-origin. A production build requires an absolute URL — Vercel Production holds the Railway api origin (`https://api-production-903f.up.railway.app` today, `https://api.<domain>` once a domain exists); previews derive it (see RAILWAY_PR_API_URL_TEMPLATE).",
  },
  {
    name: "VITE_APP_ENV",
    services: ["web"],
    scope: "config",
    local: "development",
    railway: "n/a",
    vercel: "both",
    setBy: "template",
    format: "enum",
    values: ["development", "preview", "production"],
    files: ["web"],
    description:
      "development | preview | production. Only `production` loads Vercel Speed Insights. On Vercel `scripts/vercel-env.ts` sets it from VERCEL_ENV at build time.",
  },
  {
    name: "VITE_DEV_API_TARGET",
    services: ["web"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    format: "url",
    runtimeOnly: true,
    files: ["web"],
    description:
      "Where the Vite dev proxy forwards `/api/*` (default `http://localhost:3001`). Read by `vite.config.ts` only, never bundled.",
  },
  {
    name: "RAILWAY_PR_API_URL_TEMPLATE",
    services: ["web"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "preview",
    setBy: "manual",
    runtimeOnly: true,
    description:
      "Vercel Preview only. `https://api-ai-teacher-pr-{pr}.up.railway.app` (Railway names PR environments after the GitHub repo, `ai-teacher-pr-<n>`; confirmed with PR #30): `scripts/vercel-env.ts` replaces `{pr}` with VERCEL_GIT_PULL_REQUEST_ID to point the preview at the Railway PR api. Never in a local .env.",
  },
  {
    name: "VITE_API_URL_FALLBACK",
    services: ["web"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "preview",
    setBy: "manual",
    runtimeOnly: true,
    description:
      "Vercel Preview only. API origin for preview builds without a PR number (branch pushes) or without a template — point it at the Railway production api (`https://api-production-903f.up.railway.app`). Never in a local .env.",
  },
  {
    name: "E2E_VERBOSE",
    services: ["web"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    runtimeOnly: true,
    description:
      "Any value makes `playwright.config.ts` pipe api/worker logs at level info instead of discarding them. Shell only.",
  },

  // --- CI / tooling ----------------------------------------------------------------------------------
  {
    name: "CI",
    services: ["ci"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    runtimeOnly: true,
    description:
      "`true` on GitHub Actions. `test:db` then skips docker compose, Playwright uses CI settings, `bun test` enables coverage.",
  },
  {
    name: "CI_STRICT",
    services: ["ci"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    runtimeOnly: true,
    description:
      'Repository variable. `true` makes the gated `test` and `e2e` jobs blocking (README "CI").',
  },
  {
    name: "REQUIRE_TEST_DB",
    services: ["ci", "compose"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "template",
    runtimeOnly: true,
    description:
      "`1` makes DB-backed suites fail instead of skipping when TEST_DATABASE_URL is unreachable. Set by `bun run test:db` and CI.",
  },
  {
    name: "TURBO_TOKEN",
    services: ["ci"],
    scope: "secret",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    runtimeOnly: true,
    description:
      "Repository secret: Vercel token for the Turborepo remote cache (ADR 0002). Empty = no remote cache.",
  },
  {
    name: "TURBO_TEAM",
    services: ["ci"],
    scope: "config",
    local: null,
    railway: "n/a",
    vercel: "n/a",
    setBy: "manual",
    runtimeOnly: true,
    description:
      "Repository variable: Vercel team slug for the remote cache (`omerbresinskis-projects`).",
  },
] as const satisfies readonly EnvVar[];

export type EnvName = (typeof CONTRACT)[number]["name"];

/** Every declared variable, in matrix order (element type widened to `EnvVar` with a narrow name). */
export const ENV_CONTRACT: readonly (EnvVar & { readonly name: EnvName })[] = CONTRACT;

/** `ENV.DATABASE_URL === "DATABASE_URL"` — use these instead of string literals. */
export const ENV = Object.fromEntries(ENV_CONTRACT.map((v) => [v.name, v.name])) as {
  readonly [K in EnvName]: K;
};

/** `turbo.json#env` may also list these globs (Turborepo wildcard syntax). */
export const TURBO_ENV_GLOBS = ["PLAYWRIGHT_*"] as const;

/** Generated `.env.example` files: path (from the repo root) and header comment. */
export const ENV_FILES: Readonly<
  Record<EnvFile, { readonly path: string; readonly header: string }>
> = {
  root: {
    path: ".env.example",
    header: `# Teaching Journey -- root environment for LOCAL development (TEACH-18, TEACH-26).
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# \`bun run setup\` copies this file to \`.env\` once and never overwrites it. \`.env\` is gitignored.
# Everything here targets the docker-compose Postgres only; never put production credentials in
# a local env file (F15 section 5: development uses synthetic data only).
#
# Who reads the root \`.env\`:
#   - docker compose: reads \`.env\` from this directory automatically (ports below).
#   - the root scripts (\`bun run setup | dev | doctor | db:*\`): Bun loads \`.env\` from the cwd.
#   - workspaces (apps/*, packages/*) do NOT see this file. Each app/package that reads env keeps
#     its own \`.env.example\` -> \`.env\` next to its package.json (ADR 0015); \`setup\` copies those
#     too and \`doctor\` validates every \`.env\` against docs/env.md.`,
  },
  api: {
    path: "apps/api/.env.example",
    header: `# @tj/api -- local settings for \`bun run dev\` / \`bun test\` inside apps/api (ADR 0015).
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# Bun loads \`.env\` from the process cwd only, so this file is what the API sees when started from
# this directory (turbo does not load env files). \`bun run setup\` copies it to \`.env\` once and
# generates BETTER_AUTH_SECRET. Real values live in Railway; never commit secrets. See docs/env.md.`,
  },
  worker: {
    path: "apps/worker/.env.example",
    header: `# @tj/worker -- copied to \`.env\` by \`bun run setup\` (never overwritten). Bun loads \`.env\` from
# the process cwd only, so \`bun run dev\` inside apps/worker reads this file.
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# Local development uses synthetic data only -- never point DATABASE_URL at production.`,
  },
  web: {
    path: "apps/web/.env.example",
    header: `# @tj/web -- copied to \`.env\` by \`bun run setup\` (never overwritten). Vite exposes only variables
# prefixed VITE_ to the browser bundle; they are validated at module load in src/env.ts (ADR 0015).
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# On Vercel both VITE_* values are resolved at build time by scripts/vercel-env.ts (repo root):
#   Production  -> VITE_APP_ENV=production, VITE_API_URL from the project's Production variable
#   Preview     -> VITE_APP_ENV=preview,  VITE_API_URL = RAILWAY_PR_API_URL_TEMPLATE with {pr}
#                  replaced by VERCEL_GIT_PULL_REQUEST_ID, else VITE_API_URL_FALLBACK
# RAILWAY_PR_API_URL_TEMPLATE and VITE_API_URL_FALLBACK are Vercel Preview variables only --
# they are never read by the app and do not belong in a local .env (docs/env.md).`,
  },
  db: {
    path: "packages/db/.env.example",
    header: `# @tj/db -- local settings for \`bun run db:generate | db:studio | test\` inside packages/db.
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# Bun loads \`.env\` from the process cwd only, so this file is what drizzle-kit and \`bun test\`
# see when run from this directory. The root scripts (\`bun run setup | db:migrate | test:db\`)
# pass DATABASE_URL and TEST_DATABASE_URL explicitly and do not need it.
#
# Keep the port in sync with TJ_PG_PORT in the root \`.env\`. Local development uses synthetic
# data only (F15 section 5) -- never point these at production.`,
  },
  jobs: {
    path: "packages/jobs/.env.example",
    header: `# @tj/jobs -- local settings for \`bun test\` inside packages/jobs.
#
# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
# Bun loads \`.env\` from the process cwd only. The integration tests connect to TEST_DATABASE_URL
# (never DATABASE_URL), truncate its tables and install pg-boss into the \`pgboss_test\` schema.
# They skip visibly when this is unset or the server is unreachable.`,
  },
};

// --- derived views (pure helpers shared by the generators, doctor and env:check) -----------------

export interface ResolvedPlacement {
  readonly file: EnvFile;
  readonly commented: boolean;
  /** `null` only when commented (no example value). */
  readonly value: string | null;
}

/** Normalises `files` for one variable. */
export function placementsOf(v: EnvVar): ResolvedPlacement[] {
  return (v.files ?? []).map((p) => {
    const placement = typeof p === "string" ? { file: p } : p;
    const value = placement.value ?? v.local;
    return {
      file: placement.file,
      commented: placement.commented ?? value === null,
      value,
    };
  });
}

/** Variables (in contract order) that appear in `file`, with their resolved placement. */
export function varsForFile(file: EnvFile): { v: EnvVar; placement: ResolvedPlacement }[] {
  const out: { v: EnvVar; placement: ResolvedPlacement }[] = [];
  for (const v of ENV_CONTRACT) {
    const placement = placementsOf(v).find((p) => p.file === file);
    if (placement) out.push({ v, placement });
  }
  return out;
}

/**
 * Keys `doctor` requires in the `.env` next to `file`: every uncommented key of the example plus
 * `generated` secrets (which the example only documents commented-out, but `setup` creates).
 */
export function requiredKeysForFile(file: EnvFile): string[] {
  return varsForFile(file)
    .filter(({ v, placement }) => !placement.commented || v.setBy === "generated")
    .map(({ v }) => v.name);
}

/** Contract names a given service reads (schema + runtime-only). */
export function namesForService(service: EnvService): string[] {
  return ENV_CONTRACT.filter((v) => (v.services as readonly EnvService[]).includes(service)).map(
    (v) => v.name,
  );
}

/** Names the service's boot-time Zod schema is expected to declare (excludes `runtimeOnly`). */
export function schemaNamesForService(service: EnvService): string[] {
  return ENV_CONTRACT.filter(
    (v) => (v.services as readonly EnvService[]).includes(service) && !v.runtimeOnly,
  ).map((v) => v.name);
}

export type RailwayEnvironment = "production" | "pr";
export type VercelEnvironment = "production" | "preview";

/** Names expected on the Railway service `api` / `worker` in `environment`. */
export function railwayNames(service: "api" | "worker", environment: RailwayEnvironment): string[] {
  const want: RailwayTarget = environment === "production" ? "prod" : "pr";
  return ENV_CONTRACT.filter(
    (v) =>
      (v.services as readonly EnvService[]).includes(service) &&
      (v.railway === "both" || v.railway === want),
  ).map((v) => v.name);
}

/** Names expected on the Vercel project in `environment`. */
export function vercelNames(environment: VercelEnvironment): string[] {
  const want: VercelTarget = environment === "production" ? "prod" : "preview";
  return ENV_CONTRACT.filter(
    (v) =>
      (v.services as readonly EnvService[]).includes("web") &&
      (v.vercel === "both" || v.vercel === want),
  ).map((v) => v.name);
}

/** Secret-scoped names (gitleaks rules, rotation docs). */
export function secretNames(): string[] {
  return ENV_CONTRACT.filter((v) => v.scope === "secret").map((v) => v.name);
}

/** Look a variable up by name. */
export function envVar(name: string): EnvVar | undefined {
  return ENV_CONTRACT.find((v) => v.name === name);
}
