import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";

import { cn } from "../lib/cn";

/*
 * Generated by `bunx shadcn add button` (style new-york, Tailwind v4) and adapted for @tj/ui:
 * - Shadcn semantic token names resolve to TeachDeck values in `globals.css`.
 * - `transition-*` wrapped in `motion-safe:` so `prefers-reduced-motion` is respected.
 * - `type="button"` default (native buttons default to "submit" inside forms).
 * - `import { Slot } from "radix-ui"` → `@radix-ui/react-slot` (single small dependency).
 *
 * Variants (V2-DESIGN §2.4, rulings 23 and 25):
 * - `primary` is the terracotta fill, one per bar. A bare <Button> is NOT a primary: `default`
 *   is the quiet button (`secondary` and `outline` are the same recipe), a strong hairline on the
 *   card surface, so a primary has to be asked for by name.
 * - `inverse` is the ink pill: fully round, ink under paper, the one quiet-strong action on a
 *   screen (dayback's "Build the live view"). It is not a second primary.
 * - Weight is the rung: fills and the quiet button carry 600, ghost and link 500. A ghost is a
 *   bar's text action; at 600 it shouts as loudly as the primary beside it.
 * - Press is a colour step (`--*-press`), never a brightness filter.
 * - Sizes read the height ladder tokens: xs 28, sm 32, default 36 (`lg` is the same rung).
 */

const quiet =
  "border border-border-strong bg-card text-foreground hover:bg-accent active:bg-accent-active disabled:border-border";

const buttonVariants = cva(
  "inline-flex shrink-0 items-center justify-center gap-2 rounded-control text-sm font-semibold whitespace-nowrap outline-none motion-safe:transition-all focus-visible:shadow-focus disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: quiet,
        secondary: quiet,
        outline: quiet,
        primary:
          "bg-primary-fill text-primary-foreground hover:bg-primary-fill-hover active:bg-primary-fill-press",
        inverse:
          "rounded-pill bg-inverse text-inverse-foreground hover:bg-inverse-hover active:bg-inverse-press",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive-hover active:bg-destructive-press",
        ghost:
          "font-medium text-ink-2 hover:bg-accent hover:text-foreground active:bg-accent-active",
        link: "font-medium text-brand-text underline-offset-4 hover:underline",
      },
      size: {
        default: "h-(--button-height-lg) px-4 has-[>svg]:px-3",
        lg: "h-(--button-height-lg) px-4 has-[>svg]:px-3",
        sm: "h-(--button-height) gap-1.5 px-3 has-[>svg]:px-2.5",
        xs: "h-(--button-height-xs) gap-1 px-2.5 text-xs has-[>svg]:px-2 [&_svg:not([class*='size-'])]:size-3.5",
        icon: "size-9",
        "icon-xs": "size-7 [&_svg:not([class*='size-'])]:size-3.5",
        "icon-sm": "size-8",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

export type ButtonProps = React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    /** Render the child element instead of a `<button>` (Radix Slot), e.g. for router links. */
    asChild?: boolean;
  };

function Button({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  type,
  ...props
}: ButtonProps) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      // Recorded contrast exception (ADR 0019 §4 amendment): axe treats this surface as advisory.
      data-primary-fill={variant === "primary" ? "" : undefined}
      data-size={size}
      // Only native <button> gets the default; a slotted <a> must not receive type="button".
      type={asChild ? type : (type ?? "button")}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };
