import type * as React from "react";

import { cn } from "../lib/cn";

/*
 * Generated by `bunx shadcn add card` (style new-york, Tailwind v4) and adapted for @tj/ui:
 * Shadcn semantic token names resolve to TeachDeck values in `globals.css`.
 */

export type CardProps = React.ComponentProps<"div"> & {
  variant?: "default" | "contained";
  thumbnail?: React.ReactNode;
  overlay?: React.ReactNode;
  heading?: React.ReactNode;
  meta?: React.ReactNode;
  aspect?: "16:9" | "4:3";
};

function Card({
  className,
  variant = "default",
  thumbnail,
  overlay,
  heading,
  meta,
  aspect = "16:9",
  children,
  ...props
}: CardProps) {
  if (variant === "contained") {
    return (
      <div
        data-slot="card"
        // Do not add isolate: card actions must sit above the sibling cover link's z-index.
        className={cn(
          "flex flex-col overflow-hidden rounded-face bg-card text-card-foreground shadow-1 hover:shadow-2 focus-within:shadow-2",
          className,
        )}
        {...props}
      >
        <div
          data-slot="card-thumbnail"
          className={cn(
            "relative order-1 shrink-0 border-b border-border",
            aspect === "16:9" ? "aspect-video" : "aspect-[4/3]",
          )}
        >
          {thumbnail}
          {overlay}
        </div>
        <div data-slot="card-footer" className="order-2 flex flex-col gap-1 px-4 py-3">
          {heading ? (
            <div
              data-slot="card-heading"
              className="truncate text-lead font-semibold text-foreground"
            >
              {heading}
            </div>
          ) : null}
          {meta ? (
            <div
              data-slot="card-meta"
              className="flex items-center gap-1.5 truncate text-meta tabular-nums text-ink-3"
            >
              {meta}
            </div>
          ) : null}
          {children}
        </div>
      </div>
    );
  }

  return (
    <div
      data-slot="card"
      className={cn(
        "flex flex-col gap-6 rounded-card border border-border bg-card py-6 text-card-foreground shadow-1",
        className,
      )}
      {...props}
    >
      {children}
    </div>
  );
}

function CardOverlay({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-overlay"
      className={cn(
        "pointer-events-none pointer-coarse:opacity-100 absolute inset-0 z-2 flex items-end justify-between bg-gradient-to-t from-black/30 p-2 opacity-0 transition-opacity duration-fast group-hover/card:opacity-100 group-focus-within/card:opacity-100",
        className,
      )}
      {...props}
    />
  );
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-2 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
        className,
      )}
      {...props}
    />
  );
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-title"
      className={cn("font-semibold leading-none", className)}
      {...props}
    />
  );
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-description"
      className={cn("text-muted-foreground text-sm", className)}
      {...props}
    />
  );
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-action"
      className={cn("col-start-2 row-span-2 row-start-1 self-start justify-self-end", className)}
      {...props}
    />
  );
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return <div data-slot="card-content" className={cn("px-6", className)} {...props} />;
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-footer"
      className={cn("flex items-center px-6 [.border-t]:pt-6", className)}
      {...props}
    />
  );
}

export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardOverlay,
  CardTitle,
};
