import { CheckIcon, MinusIcon } from "lucide-react";
import { Checkbox as CheckboxPrimitive } from "radix-ui";
import type * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * TeachDeck geometry: an 18px box with a 12px glyph. Off, the control edge is the boundary
 * (ruling 25); on or mixed, the accent fill carries the glyph. A 32px pseudo-element is the
 * hit area so the box stays 18px in its row. Radix owns semantics and keyboard interaction.
 */

function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer group/checkbox relative inline-flex size-[18px] shrink-0 items-center justify-center rounded-key border border-border-control bg-card align-middle outline-none",
        "before:absolute before:top-1/2 before:left-1/2 before:size-8 before:-translate-x-1/2 before:-translate-y-1/2 before:content-['']",
        "hover:bg-accent",
        "focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background",
        "disabled:cursor-not-allowed disabled:opacity-45",
        "aria-invalid:border-destructive",
        "data-[state=checked]:border-primary data-[state=checked]:bg-primary-fill-aa data-[state=checked]:text-primary-foreground data-[state=checked]:hover:bg-primary-fill-aa",
        "data-[state=indeterminate]:border-primary data-[state=indeterminate]:bg-primary-fill-aa data-[state=indeterminate]:text-primary-foreground data-[state=indeterminate]:hover:bg-primary-fill-aa",
        className,
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none"
      >
        <CheckIcon
          aria-hidden
          className="size-3 group-data-[state=indeterminate]/checkbox:hidden"
          strokeWidth={2.5}
        />
        <MinusIcon
          aria-hidden
          className="hidden size-3 group-data-[state=indeterminate]/checkbox:block"
          strokeWidth={2.5}
        />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  );
}

export { Checkbox };
