import type * as React from "react";

import { cn } from "../lib/cn";

/*
 * Generated by `bunx shadcn add input` (style new-york, Tailwind v4) and adapted for @tj/ui:
 * - shadcn token names → TJ tokens (`border-input` → `border-border`, `selection:bg-primary` →
 *   `selection:bg-accent`); `dark:` variants removed (theming via data-theme variables).
 * - `transition-*` wrapped in `motion-safe:`.
 */

export type InputProps = React.ComponentProps<"input">;

function Input({ className, type, ...props }: InputProps) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "h-9 w-full min-w-0 rounded-md border border-border bg-transparent px-3 py-1 text-base shadow-xs outline-none motion-safe:transition-[color,box-shadow] selection:bg-accent selection:text-accent-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50",
        "aria-invalid:border-destructive aria-invalid:ring-destructive/20",
        className,
      )}
      {...props}
    />
  );
}

export { Input };
