import type * as React from "react";

import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * Keyboard hints: a 20px cap at --radius-key (ruling 18), 12/500 in ink-3 with 0.02em tracking, on the card surface.
 * The small wrapper is intentionally decorative when nested in a tooltip.
 */

function Kbd({ className, ...props }: React.ComponentProps<"kbd">) {
  return (
    <kbd
      data-slot="kbd"
      className={cn(
        "pointer-events-none inline-flex h-5 min-w-5 items-center justify-center rounded-key border border-border bg-card px-1 text-eyebrow font-medium tracking-[0.02em] text-ink-3 select-none",
        className,
      )}
      {...props}
    />
  );
}

function KbdGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <kbd
      data-slot="kbd-group"
      className={cn("inline-flex items-center gap-1", className)}
      {...props}
    />
  );
}

export { Kbd, KbdGroup };
