import { Label as LabelPrimitive } from "radix-ui";
import type * as React from "react";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * Labels use TeachDeck's compact metadata type and secondary ink colour.
 * Radix maintains the native label association.
 */

function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={`flex items-center gap-2 text-meta font-medium text-ink-2 select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50 ${className ?? ""}`}
      {...props}
    />
  );
}

export { Label };
