"use client";

import { RadioGroup as RadioGroupPrimitive } from "radix-ui";
import type * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * A radio is round: an 18px circle with a 6px centred dot, so it never reads as a checkbox.
 * Off, the control edge is the boundary (ruling 25); on, the accent fill carries a paper dot.
 * Radix retains the roving focus and exclusive-selection contract.
 */

function RadioGroup({
  className,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Root>) {
  return (
    <RadioGroupPrimitive.Root
      data-slot="radio-group"
      className={cn("grid gap-3", className)}
      {...props}
    />
  );
}

function RadioGroupItem({
  className,
  ...props
}: React.ComponentProps<typeof RadioGroupPrimitive.Item>) {
  return (
    <RadioGroupPrimitive.Item
      data-slot="radio-group-item"
      className={cn(
        "relative inline-flex size-[18px] shrink-0 items-center justify-center rounded-full border border-border-control bg-card align-middle outline-none",
        "before:absolute before:top-1/2 before:left-1/2 before:size-8 before:-translate-x-1/2 before:-translate-y-1/2 before:content-['']",
        "hover:bg-accent",
        "focus-visible:shadow-focus",
        "disabled:cursor-not-allowed disabled:opacity-45",
        "aria-invalid:border-destructive",
        "data-[state=checked]:border-primary data-[state=checked]:bg-primary-fill-aa data-[state=checked]:text-primary-foreground data-[state=checked]:hover:bg-primary-fill-aa",
        className,
      )}
      {...props}
    >
      <RadioGroupPrimitive.Indicator
        data-slot="radio-group-indicator"
        className="flex items-center justify-center"
      >
        <span aria-hidden className="block size-1.5 rounded-full bg-current" />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  );
}

export { RadioGroup, RadioGroupItem };
