"use client";

import { Separator as SeparatorPrimitive } from "radix-ui";
import type * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * Separators draw from the shared border token in every data-theme variant.
 * Radix owns the optional semantic separator role.
 */

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px",
        className,
      )}
      {...props}
    />
  );
}

export { Separator };
