import type * as React from "react";

import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * TeachDeck skeletons use the active accent wash rather than neutral grey.
 * The control radius keeps placeholders visually aligned with inputs.
 */

function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn("animate-pulse rounded-control bg-accent-active", className)}
      {...props}
    />
  );
}

export { Skeleton };
