"use client";

import { Slider as SliderPrimitive } from "radix-ui";
import * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui (TEACH-97).
 * The TeachDeck slider (`components/ui2/Slider.tsx`) sits in a 32px control row with a 4px track
 * and a 16px thumb, and its fill is ink, not accent — Switch owns the accent in this kit. Radix
 * puts the slider role, keyboard model and `aria-valuenow` on each thumb, so the `aria-label` /
 * `aria-labelledby` given to the component is forwarded to every thumb — that is where a screen
 * reader and Testing Library look for the name.
 */

function Slider({
  className,
  defaultValue,
  value,
  min = 0,
  max = 100,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  ...props
}: React.ComponentProps<typeof SliderPrimitive.Root>) {
  const values = React.useMemo(
    () => (Array.isArray(value) ? value : Array.isArray(defaultValue) ? defaultValue : [min]),
    [value, defaultValue, min],
  );

  return (
    <SliderPrimitive.Root
      data-slot="slider"
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      className={cn(
        "relative flex h-8 w-full touch-none select-none items-center data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
        className,
      )}
      {...props}
    >
      <SliderPrimitive.Track
        data-slot="slider-track"
        className="relative h-1 w-full grow overflow-hidden rounded-full bg-border-control"
      >
        <SliderPrimitive.Range data-slot="slider-range" className="absolute h-full bg-ink-2" />
      </SliderPrimitive.Track>
      {values.map((_, index) => (
        <SliderPrimitive.Thumb
          data-slot="slider-thumb"
          // biome-ignore lint/suspicious/noArrayIndexKey: thumbs are positional; Radix keys by index too
          key={index}
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledBy}
          className="block size-4 shrink-0 rounded-full border border-border-control bg-card shadow-sm outline-none motion-safe:transition-shadow hover:ring-[3px] hover:ring-ring/50 focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none"
        />
      ))}
    </SliderPrimitive.Root>
  );
}

export { Slider };
