import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from "lucide-react";
import { Toaster as Sonner, type ToasterProps, toast } from "sonner";

import { useTheme } from "../theme/theme-provider";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * The bottom-centre stack follows TeachDeck's three-toast, four-second convention.
 * Render inside ThemeProvider; high-contrast maps to Sonner's dark colour scheme.
 */

const Toaster = ({ ...props }: ToasterProps) => {
  const { resolvedTheme } = useTheme();

  return (
    <Sonner
      theme={(resolvedTheme === "light" ? "light" : "dark") as ToasterProps["theme"]}
      position="bottom-center"
      visibleToasts={3}
      duration={4000}
      className="toaster group"
      icons={{
        success: <CircleCheckIcon className="size-4" />,
        info: <InfoIcon className="size-4" />,
        warning: <TriangleAlertIcon className="size-4" />,
        error: <OctagonXIcon className="size-4" />,
        loading: <Loader2Icon className="size-4 animate-spin" />,
      }}
      toastOptions={{
        classNames: {
          toast:
            "bg-foreground text-background rounded-card shadow-3 text-body min-h-10 max-w-[400px] px-3.5 py-2.5",
          actionButton: "bg-transparent text-background underline underline-offset-4",
        },
      }}
      {...props}
    />
  );
};

export { Toaster, toast };
