"use client";

import { Switch as SwitchPrimitive } from "radix-ui";
import type * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * TeachDeck toggle geometry: 44 by 24 track, 20px thumb inset 2. The off track is the
 * pressed wash with the control edge as a 1px boundary (ruling 25: the edge marks checkbox,
 * radio and the off toggle, never a fill). The on track is the accent fill. The 32px hit area
 * is a pseudo-element so the drawing stays 24px tall in its row.
 */

function Switch({ className, ...props }: React.ComponentProps<typeof SwitchPrimitive.Root>) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      className={cn(
        "peer group/switch relative inline-flex h-6 w-11 shrink-0 items-center rounded-full outline-none",
        "before:absolute before:top-1/2 before:left-1/2 before:h-8 before:w-[52px] before:-translate-x-1/2 before:-translate-y-1/2 before:content-['']",
        "bg-accent-active shadow-[inset_0_0_0_1px_var(--border-control)] hover:bg-accent",
        "data-[state=checked]:bg-primary data-[state=checked]:shadow-none data-[state=checked]:hover:bg-primary-hover",
        "focus-visible:shadow-focus",
        "disabled:cursor-not-allowed disabled:opacity-45",
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className="pointer-events-none block size-5 rounded-full bg-card shadow-[0_1px_2px_rgb(26_24_22/0.24)] motion-safe:transition-transform data-[state=checked]:translate-x-[22px] data-[state=unchecked]:translate-x-0.5"
      />
    </SwitchPrimitive.Root>
  );
}

export { Switch };
