import type * as React from "react";
import { cn } from "../lib/cn";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * Textareas use TeachDeck's sunken secondary surface and compact control geometry.
 * Native textarea semantics and caller-provided class names remain unchanged.
 */

function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        "flex min-h-20 w-full rounded-control border border-input bg-secondary p-2 text-body outline-none placeholder:text-ink-3 focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20",
        className,
      )}
      {...props}
    />
  );
}

export { Textarea };
