"use client";

import { Tooltip as TooltipPrimitive } from "radix-ui";
import type * as React from "react";
import { cn } from "../lib/cn";

import { Kbd } from "./kbd";

/*
 * Generated by shadcn@4.21.0 (new-york) on 2026-09-06 and adapted for @tj/ui.
 * The convenience wrapper renders TeachDeck labels and optional keyboard hints.
 * Mount TooltipProvider once in the app router's Wrap; it is intentionally not implicit.
 * `className="tj-stage"` on the content puts the portalled surface on the stage palette
 * (ADR 0022 §3): the class lands on the Radix `Content` inside the `Portal`, never on a wrapper.
 */

function TooltipProvider({
  delayDuration = 300,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Provider>) {
  return (
    <TooltipPrimitive.Provider
      data-slot="tooltip-provider"
      delayDuration={delayDuration}
      {...props}
    />
  );
}

function Tooltip({
  children,
  label,
  shortcut,
  side,
  ref,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Root> & {
  label: React.ReactNode;
  shortcut?: string;
  side?: React.ComponentProps<typeof TooltipPrimitive.Content>["side"];
  ref?: React.Ref<HTMLElement>;
}) {
  return (
    <TooltipPrimitive.Root data-slot="tooltip" {...props}>
      <TooltipPrimitive.Trigger ref={ref as React.Ref<HTMLButtonElement>} asChild>
        {children}
      </TooltipPrimitive.Trigger>
      <TooltipContent side={side}>
        <span>{label}</span>
        {shortcut ? <Kbd>{shortcut}</Kbd> : null}
      </TooltipContent>
    </TooltipPrimitive.Root>
  );
}

function TooltipTrigger({ ...props }: React.ComponentProps<typeof TooltipPrimitive.Trigger>) {
  return <TooltipPrimitive.Trigger data-slot="tooltip-trigger" {...props} />;
}

function TooltipContent({
  className,
  sideOffset = 0,
  children,
  ...props
}: React.ComponentProps<typeof TooltipPrimitive.Content>) {
  return (
    <TooltipPrimitive.Portal>
      <TooltipPrimitive.Content
        data-slot="tooltip-content"
        sideOffset={sideOffset}
        className={cn(
          "z-50 flex h-6 w-fit items-center gap-1.5 rounded-control bg-foreground px-2 text-meta text-background",
          className,
        )}
        {...props}
      >
        {children}
      </TooltipPrimitive.Content>
    </TooltipPrimitive.Portal>
  );
}

export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger };
