import type { PictureDirectorInput, PictureDirectorRoute } from "../prompts/picture-director";

/**
 * Routing fixtures for the picture director (PHOTO-BANK round 3): the 9 smoke slots of T3-R2
 * (writer requests verbatim, slide text from the saved writer outputs) and 15 written to cover a
 * named landmark, historical events, a person, artworks, generic scenes, counts, apparatus, a
 * process better drawn, unusual combinations, a locale-dependent subject and pictures that add
 * nothing. `expect` lists every route a careful teacher would accept; `split` marks where separate
 * pictures are acceptable too. The live run (PHOTO-BANK/director-run.ts) scores against these.
 */
export interface DirectorFixture {
  id: string;
  input: PictureDirectorInput;
  expect: PictureDirectorRoute[];
  split?: boolean;
}

const base = (
  yearGroup: string,
  subject: string,
  title: string,
  heading: string,
  text: string,
  point: string,
  request: string,
  mustShow: string[],
  aspect = 1.6,
): PictureDirectorInput => ({
  yearGroup,
  subject,
  title,
  country: "England",
  heading,
  text,
  point,
  request,
  mustShow,
  aspect,
});

export const DIRECTOR_FIXTURES: DirectorFixture[] = [
  // ---- the 9 smoke slots (T3-R2) ----
  {
    id: "y1-animals-s1",
    input: base(
      "Year 1",
      "Science",
      "Animals and their young",
      "Animals and their young",
      "",
      "",
      "An adult dog and its puppy sitting side by side, with both whole bodies clearly visible.",
      ["adult dog", "puppy"],
      1.78,
    ),
    expect: ["pexels"],
  },
  {
    id: "y1-animals-s3",
    input: base(
      "Year 1",
      "Science",
      "Animals and their young",
      "Dogs and cats",
      "A young dog is a puppy. A young cat is a kitten.",
      "Point to each animal as you name it. Explain that young means an animal near the start of its life. Pupils repeat dog and puppy, then cat and kitten.",
      "A two-panel photographic collage: an adult dog beside a puppy on the left; an adult cat beside a kitten on the right. All animals are clearly visible.",
      ["adult dog", "puppy", "adult cat"],
      0.89,
    ),
    expect: ["library-or-generate", "pexels"],
    split: true,
  },
  {
    id: "y1-animals-s4",
    input: base(
      "Year 1",
      "Science",
      "Animals and their young",
      "On the farm",
      "A young cow is a calf. A young sheep is a lamb. A young hen is a chick.",
      "Point to each adult and its young. Say each pair slowly and ask pupils to repeat it.",
      "A three-panel photographic collage: an adult cow beside a calf; an adult sheep beside a young lamb; an adult hen beside a small yellow chick. Show each animal's whole body.",
      ["adult cow", "calf", "adult sheep"],
      0.89,
    ),
    expect: ["library-or-generate", "pexels"],
    split: true,
  },
  {
    id: "y1-animals-s7",
    input: base(
      "Year 1",
      "Science",
      "Animals and their young",
      "Look at their bodies",
      "Both have four legs and two ears. Both have wool on their bodies. This sheep has more wool than this lamb.",
      "Explain that a body covering is what covers an animal's body. Point out the wool. Model comparing body parts and coverings.",
      "A full-grown unshorn sheep with a thick woolly fleece beside a small young lamb with a short woolly coat. Both stand side on, with four legs and two ears clearly visible.",
      ["full-grown unshorn sheep", "small young lamb"],
      0.89,
    ),
    expect: ["pexels"],
  },
  {
    id: "y5-fractions-s1",
    input: base(
      "Year 5",
      "Maths",
      "Fractions of amounts",
      "Fractions of amounts",
      "",
      "",
      "24 identical counters arranged in four equal groups of six on a classroom table",
      ["24 identical counters"],
      1.78,
    ),
    expect: ["code"],
  },
  {
    id: "y7-particles-s1",
    input: base(
      "Year 7",
      "Science",
      "The particle model",
      "The particle model",
      "",
      "",
      "An ice cube beside a glass of liquid water, showing a solid keeping its shape and a liquid taking the shape of its container",
      ["ice cube", "glass of liquid water"],
      1.78,
    ),
    expect: ["pexels", "library-or-generate"],
  },
  {
    id: "y9-weimar-s1",
    input: base(
      "Year 9",
      "History",
      "Weimar Germany: the hyperinflation crisis of 1923",
      "Weimar Germany: the hyperinflation crisis of 1923",
      "",
      "",
      "German children playing with bundles of worthless banknotes during the hyperinflation crisis of 1923",
      ["German children", "bundles of worthless banknotes"],
      1.78,
    ),
    expect: ["commons"],
  },
  {
    id: "y10-tempest-s1",
    input: base(
      "Year 10",
      "English",
      "The Tempest: Prospero and the mechanics of power",
      "The Tempest: Prospero and the mechanics of power",
      "",
      "",
      "A theatre production of The Tempest showing Prospero holding a staff, with Ariel and Caliban nearby",
      ["theatre production of The Tempest", "Prospero", "staff"],
      1.78,
    ),
    expect: ["commons"],
  },
  {
    id: "y11-rates-s1",
    input: base(
      "Year 11",
      "Chemistry",
      "Rates of reaction",
      "Rates of reaction",
      "",
      "",
      "School chemistry experiment showing marble chips reacting with dilute hydrochloric acid in a conical flask connected to a gas syringe",
      ["School chemistry experiment"],
      1.78,
    ),
    expect: ["library-or-generate", "pexels"],
  },
  // ---- 15 written for coverage ----
  {
    id: "landmark-cliffs",
    input: base(
      "Year 8",
      "Geography",
      "Coastal erosion",
      "Chalk cliffs",
      "Chalk is a soft rock. Waves erode the base of the cliff.",
      "Show how waves attack the foot of a chalk cliff and the cliff retreats.",
      "The White Cliffs of Dover seen from the sea, showing the chalk cliff face and the waves at its base",
      ["White Cliffs of Dover", "waves at the base"],
    ),
    expect: ["commons"],
  },
  {
    id: "event-great-fire",
    input: base(
      "Year 2",
      "History",
      "The Great Fire of London, 1666",
      "London is burning",
      "The fire started in a bakery. It spread fast because the houses were made of wood.",
      "Pupils describe what they see: flames, smoke, wooden houses, people escaping by boat.",
      "A painting of the Great Fire of London in 1666, with flames over the city and people escaping on the river",
      ["Great Fire of London", "flames", "boats on the river"],
    ),
    expect: ["commons"],
  },
  {
    id: "person-darwin",
    input: base(
      "Year 6",
      "Science",
      "Evolution and inheritance",
      "Charles Darwin",
      "Darwin sailed on HMS Beagle. He studied finches on the Galapagos Islands.",
      "Introduce Darwin as the scientist who explained evolution by natural selection.",
      "A portrait photograph of Charles Darwin as an old man",
      ["Charles Darwin"],
      0.8,
    ),
    expect: ["commons"],
  },
  {
    id: "artwork-starry-night",
    input: base(
      "Year 8",
      "Art",
      "Post-Impressionism",
      "Movement in paint",
      "Van Gogh used thick, swirling brushstrokes.",
      "Pupils point out how the brushstrokes make the sky look as if it is moving.",
      "Van Gogh's painting The Starry Night, showing the swirling brushstrokes in the sky",
      ["The Starry Night", "swirling brushstrokes"],
    ),
    expect: ["commons"],
  },
  {
    id: "event-moon-landing",
    input: base(
      "Year 4",
      "Science",
      "Earth and space",
      "People on the Moon",
      "In 1969 astronauts walked on the Moon.",
      "Use the photo to show the Moon's dusty, grey surface and the black sky.",
      "An astronaut standing on the Moon's surface during the Apollo 11 landing in 1969",
      ["astronaut", "Moon's surface"],
    ),
    expect: ["commons"],
  },
  {
    id: "generic-rainy-street",
    input: base(
      "Year 3",
      "Geography",
      "Weather and climate",
      "Rainy days",
      "Rain falls from clouds. We use umbrellas and coats to stay dry.",
      "Pupils name the clues that show it is raining.",
      "A rainy town street with people walking under umbrellas",
      ["rain", "people with umbrellas"],
    ),
    expect: ["pexels"],
  },
  {
    id: "species-ladybird",
    input: base(
      "Year 4",
      "Science",
      "Classifying living things",
      "Insects",
      "An insect has six legs and three body parts.",
      "Pupils count the legs and find the three body parts.",
      "A close-up of a ladybird on a leaf, showing its spotted wing cases and six legs",
      ["ladybird", "six legs", "spotted wing cases"],
    ),
    expect: ["pexels"],
  },
  {
    id: "locale-coins",
    input: base(
      "Year 2",
      "Maths",
      "Money",
      "Coins we use",
      "Each coin has a value. We can add coins to make an amount.",
      "Pupils name each coin and its value.",
      "A handful of coins of different values spread out on a table",
      ["coins of different values"],
    ),
    expect: ["pexels", "library-or-generate"],
  },
  {
    id: "apparatus-filtration",
    input: base(
      "Year 7",
      "Science",
      "Separating mixtures",
      "Filtration",
      "Filtration separates an insoluble solid from a liquid.",
      "Point out the filter paper, the residue left on it and the clear filtrate below.",
      "Filtration apparatus: a filter funnel lined with filter paper over a beaker, with muddy water poured in and clear water dripping through",
      ["filter funnel", "filter paper", "beaker"],
      0.89,
    ),
    expect: ["pexels", "library-or-generate", "code"],
  },
  {
    id: "count-array-dots",
    input: base(
      "Year 2",
      "Maths",
      "Multiplication arrays",
      "Arrays",
      "3 rows of 5 make 15. 3 × 5 = 15.",
      "Pupils count the rows and how many are in each row.",
      "15 dots arranged in 3 rows of 5",
      ["15 dots"],
      1.2,
    ),
    expect: ["code"],
  },
  {
    id: "count-apples",
    input: base(
      "Year 1",
      "Maths",
      "Counting to 10",
      "How many?",
      "Count the apples. There are 7.",
      "Pupils touch-count each apple once.",
      "Seven red apples in a row on a table",
      ["seven red apples"],
    ),
    expect: ["code"],
  },
  {
    id: "process-water-cycle",
    input: base(
      "Year 4",
      "Science",
      "States of matter",
      "The water cycle",
      "Water evaporates, condenses into clouds, falls as rain and flows back to the sea.",
      "Trace the cycle in order and name each change of state.",
      "A photo showing water evaporating from the sea, forming clouds, raining over hills and flowing back to the sea in rivers",
      ["sea", "clouds", "rain"],
    ),
    expect: ["code"],
  },
  {
    id: "unusual-habitats",
    input: base(
      "Year 2",
      "Science",
      "Living things and their habitats",
      "Different habitats",
      "A polar bear lives in the Arctic. A camel lives in the desert. A monkey lives in the rainforest.",
      "Pupils match each animal to its habitat and say why it suits it.",
      "A polar bear, a camel and a monkey each in its own habitat",
      ["polar bear", "camel", "monkey"],
    ),
    expect: ["library-or-generate", "pexels"],
    split: true,
  },
  {
    id: "nothing-equations",
    input: base(
      "Year 10",
      "Maths",
      "Simultaneous equations",
      "Solving by elimination",
      "Make one coefficient match, then subtract the equations to remove that variable.",
      "Model the elimination method step by step on the board.",
      "A student thinking hard while solving equations at a desk",
      ["student", "equations"],
    ),
    expect: ["none"],
  },
  {
    id: "nothing-persuasion",
    input: base(
      "Year 9",
      "English",
      "Persuasive writing",
      "Rhetorical questions",
      "A rhetorical question makes the reader think without expecting an answer.",
      "Pupils spot rhetorical questions in the extract and explain their effect.",
      "A person giving a speech at a podium to an audience",
      ["person giving a speech"],
    ),
    expect: ["none"],
  },
  // ---- HISTORY-TEST (ruling 163): an event, a named person, a particular artefact ----
  {
    id: "history-jarrow",
    input: base(
      "Year 9",
      "History",
      "Britain in the 1930s",
      "The Jarrow Crusade",
      "In 1936, 200 men marched from Jarrow to London to ask for work.",
      "Explain why the marchers walked to London and what they wanted.",
      "The Jarrow marchers walking along a road in 1936, carrying their banner",
      ["marchers on a road", "banner"],
    ),
    expect: ["commons"],
  },
  {
    id: "history-henry-viii",
    input: base(
      "Year 8",
      "History",
      "The Tudors",
      "Henry VIII",
      "Henry VIII ruled England from 1509 to 1547.",
      "Introduce Henry VIII and how he showed his power.",
      "A portrait of King Henry VIII",
      ["Henry VIII"],
      0.8,
    ),
    expect: ["commons"],
  },
  {
    id: "history-sutton-hoo",
    input: base(
      "Year 7",
      "History",
      "Anglo-Saxon England",
      "The Sutton Hoo helmet",
      "The helmet was found in a ship burial in Suffolk.",
      "Pupils describe what the helmet tells us about its owner.",
      "The Sutton Hoo helmet, showing its face mask and decorated panels",
      ["helmet", "face mask"],
    ),
    expect: ["commons"],
  },
];
