// r5: the prompt folders' diagram kinds and spec schemas, written from the drawer's own schema (the
// one source of truth), never typed out by hand. prompts/shared/schema_parts.py reads `kinds`; the
// spec call sends `specSchemas[kind]` (services.ts `diagramJsonSchema`).
// bun lab/bakeoff/diagram-kinds.ts <prompts/shared/diagram-kinds.json>
import { writeFileSync } from "node:fs";
import { DIAGRAM_KINDS, diagramJsonSchema } from "../../packages/slides/src/diagrams/index";

export function diagramKindsFile() {
  return {
    note: "generated by lab/bakeoff/diagram-kinds.ts from the drawer's DiagramSpecSchema; do not edit",
    kinds: DIAGRAM_KINDS,
    specSchemas: Object.fromEntries(DIAGRAM_KINDS.map((k) => [k, diagramJsonSchema(k)])),
  };
}

if (import.meta.main) {
  const out = process.argv[2] ?? "diagram-kinds.json";
  writeFileSync(out, `${JSON.stringify(diagramKindsFile(), null, 1)}\n`);
  console.log("wrote", out);
}
