/**
 * Pure validation of a local `.env` against `infra/env.contract.ts`, used by `bun run doctor`.
 * Values never leave this module: results carry names and the expected shape only.
 */
import {
  type EnvFile,
  type EnvFormat,
  type EnvVar,
  requiredKeysForFile,
  varsForFile,
} from "../../infra/env.contract";
import { parseEnv } from "./env";

export interface InvalidValue {
  name: string;
  /** Human-readable expectation, e.g. `a URL`, `a port (1-65535)`, `one of lax | none | strict`. */
  expected: string;
}

export interface EnvFileReport {
  /** `false` when the `.env` is absent (then every required key is `missing`). */
  exists: boolean;
  /** Required keys (uncommented in the example, or generated by `setup`) absent or blank. */
  missing: string[];
  /** Present keys whose value does not match the contract's `format`. */
  invalid: InvalidValue[];
  /** Present keys the contract does not list for this file (informational). */
  extra: string[];
}

const ORIGIN_RE = /^https?:\/\/[^/\s]+$/;

function isUrl(value: string, protocols?: RegExp): boolean {
  try {
    const u = new URL(value);
    return protocols ? protocols.test(u.protocol.replace(/:$/, "")) : true;
  } catch {
    return false;
  }
}

function isPort(value: string): boolean {
  const n = Number(value);
  return Number.isInteger(n) && n >= 1 && n <= 65535;
}

/** `null` when `value` satisfies `format`, else what was expected. */
export function checkFormat(
  format: EnvFormat | undefined,
  value: string,
  values?: readonly string[],
): string | null {
  switch (format) {
    case undefined:
    case "string":
      return null;
    case "url":
      return isUrl(value, /^https?$/) ? null : "an absolute http(s) URL";
    case "postgres-url":
      return isUrl(value, /^postgres(ql)?$/) ? null : "a postgres:// URL";
    case "port":
      return isPort(value) ? null : "a port (1-65535)";
    case "int":
      return /^\d+$/.test(value) ? null : "an integer";
    case "number":
      return /^\d+(\.\d+)?$/.test(value) ? null : "a non-negative number";
    case "enum": {
      const allowed = values ?? [];
      return allowed.includes(value) ? null : `one of ${allowed.join(" | ")}`;
    }
    case "origin-list": {
      const items = value
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      return items.length > 0 && items.every((o) => ORIGIN_RE.test(o))
        ? null
        : "comma-separated origins (scheme://host[:port], no path)";
    }
    case "origin-pattern-list": {
      const items = value
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      return items.every((o) => ORIGIN_RE.test(o) && o.includes("*"))
        ? null
        : "comma-separated origin globs containing `*` (no path)";
    }
  }
}

/** Validates the dotenv text of the `.env` that belongs to `file`. `null` text = file missing. */
export function validateEnvFile(file: EnvFile, envText: string | null): EnvFileReport {
  const required = requiredKeysForFile(file);
  if (envText === null) return { exists: false, missing: required, invalid: [], extra: [] };

  const present = parseEnv(envText);
  const known = new Map<string, EnvVar>(varsForFile(file).map(({ v }) => [v.name, v]));

  const missing = required.filter((k) => (present.get(k) ?? "").trim() === "");
  const invalid: InvalidValue[] = [];
  for (const [name, raw] of present) {
    const v = known.get(name);
    const value = raw.trim();
    if (!v || value === "") continue;
    const expected = checkFormat(v.format, value, v.values);
    if (expected) invalid.push({ name, expected });
  }
  const extra = [...present.keys()].filter((k) => !known.has(k));
  return { exists: true, missing, invalid, extra };
}
