/**
 * Pure renderers for everything derived from `infra/env.contract.ts`: the `.env.example` files,
 * `docs/env.md` and `.gitleaks.toml`. `scripts/env-generate.ts` writes (or checks) the results.
 * Nothing here reads the file system, so every output can be unit-tested as a string.
 */
import {
  ENV_CONTRACT,
  ENV_FILES,
  type EnvFile,
  type EnvService,
  type EnvVar,
  type RailwayEnvironment,
  railwayNames,
  secretNames,
  type VercelEnvironment,
  varsForFile,
  vercelNames,
} from "../../infra/env.contract";

const WRAP = 98;

/** Word-wraps `text` into `# ` comment lines. */
export function commentLines(text: string): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "#";
  for (const word of words) {
    if (current.length + 1 + word.length > WRAP && current !== "#") {
      lines.push(current);
      current = `# ${word}`;
    } else {
      current = current === "#" ? `# ${word}` : `${current} ${word}`;
    }
  }
  if (current !== "#") lines.push(current);
  return lines;
}

function scopeNote(v: EnvVar): string | null {
  const notes: string[] = [];
  if (v.scope === "secret") notes.push("SECRET -- never commit a real value");
  if (v.setBy === "generated") notes.push("generated by `bun run setup` when missing");
  if (v.format === "enum" && v.values) notes.push(`one of: ${v.values.join(" | ")}`);
  return notes.length > 0 ? `(${notes.join("; ")})` : null;
}

/** One `.env.example` file, header + every key in contract order. */
export function renderEnvExample(file: EnvFile): string {
  const { header } = ENV_FILES[file];
  const blocks: string[] = [header.trimEnd()];
  for (const { v, placement } of varsForFile(file)) {
    const lines = commentLines(v.description);
    const note = scopeNote(v);
    if (note) lines.push(...commentLines(note));
    const value = placement.value ?? "";
    lines.push(placement.commented ? `# ${v.name}=${value}` : `${v.name}=${value}`);
    blocks.push(lines.join("\n"));
  }
  return `${blocks.join("\n\n")}\n`;
}

// --- docs/env.md ------------------------------------------------------------------------------------

const SERVICE_ORDER: readonly EnvService[] = ["api", "worker", "web", "ci", "compose"];

function code(s: string): string {
  return `\`${s}\``;
}

function cell(s: string): string {
  return s.replaceAll("|", "\\|");
}

function localCell(v: EnvVar): string {
  if (v.local !== null) return code(v.local);
  if (v.setBy === "generated") return "generated by `setup`";
  return "—";
}

/** The matrix. Column order is fixed; do not reorder without updating `docs/env.md` readers. */
export function renderMatrix(): string {
  const header =
    "| Variable | Services | Scope | Local (`.env.example`) | Railway | Vercel | Set by | Description |";
  const sep = "| --- | --- | --- | --- | --- | --- | --- | --- |";
  const rows = ENV_CONTRACT.map((v) => {
    const services = SERVICE_ORDER.filter((s) => (v.services as readonly EnvService[]).includes(s));
    return `| ${[
      code(v.name),
      services.join(", "),
      v.scope,
      localCell(v),
      v.railway,
      v.vercel,
      v.setBy ?? "—",
      cell(v.description),
    ].join(" | ")} |`;
  });
  return [header, sep, ...rows].join("\n");
}

function namesList(names: string[]): string {
  return names.length > 0 ? names.map(code).join(", ") : "—";
}

function railwaySection(): string {
  const targets: { service: "api" | "worker"; env: RailwayEnvironment }[] = [
    { service: "api", env: "production" },
    { service: "api", env: "pr" },
    { service: "worker", env: "production" },
    { service: "worker", env: "pr" },
  ];
  return targets
    .map(
      ({ service, env }) =>
        `- Railway \`${service}\` / ${env === "pr" ? "`pr-<n>`" : "`production`"}: ${namesList(
          railwayNames(service, env),
        )}`,
    )
    .join("\n");
}

function vercelSection(): string {
  const envs: VercelEnvironment[] = ["production", "preview"];
  return envs
    .map((env) => `- Vercel \`teaching-journey-web\` / \`${env}\`: ${namesList(vercelNames(env))}`)
    .join("\n");
}

function bySetBy(): string {
  const groups: Record<string, string[]> = {};
  for (const v of ENV_CONTRACT) {
    const key = v.setBy ?? "unspecified";
    const list = groups[key] ?? [];
    list.push(v.name);
    groups[key] = list;
  }
  const explain: Record<string, string> = {
    generated:
      "random, created for you — locally by `bun run setup` (appended to `apps/api/.env`, never printed), on Railway by `infra/railway/provision.sh` (`openssl rand -base64 32 | railway variable set NAME --stdin`)",
    reference:
      "a Railway reference / template such as `$" +
      "{{postgres.POSTGRES_PASSWORD}}` or `https://$" +
      "{{RAILWAY_PUBLIC_DOMAIN}}`, seeded by `provision.sh` (`bun scripts/railway-vars.ts <service>` prints the exact list)",
    template:
      "a plain, non-secret value with a known default — seeded by `provision.sh` / `vercel env add` / `.env.example`",
    manual:
      "a human pastes it: OAuth credentials, tokens, real domains. `bun run env:check --fix` prints the exact `railway variable set` / `vercel env add` command (with a placeholder, never a value)",
  };
  return (["generated", "reference", "template", "manual", "unspecified"] as const)
    .filter((key) => groups[key] !== undefined)
    .map((key) => `- **${key}** — ${explain[key] ?? ""}\n  ${namesList(groups[key] ?? [])}`)
    .join("\n");
}

function rotationSection(): string {
  const secrets = secretNames();
  const lines = [
    `Secret-scoped variables: ${namesList(secrets)}.`,
    "",
    "1. Generate the new value **without printing it**, e.g. `openssl rand -base64 32 > /tmp/secret` (or let the provider's console generate it).",
    "2. Set it in the provider, values via stdin so nothing lands in shell history or logs:",
    "   - Railway: `railway variable set NAME --stdin --service api < /tmp/secret` (repeat with `--environment pr-<n>` for an open PR environment; `--skip-deploys` to batch, then `railway redeploy --service api --yes`).",
    "   - Vercel: `vercel env rm NAME production --yes && vercel env add NAME production --sensitive < /tmp/secret` — then redeploy.",
    "   - GitHub Actions: `gh secret set NAME --repo OmerBresinski/ai-teacher < /tmp/secret`.",
    "3. `rm /tmp/secret`; run `bun run env:check` — it compares **names only** and confirms nothing is missing or extra.",
    "4. Locally: delete the line from the relevant `.env` and run `bun run setup` (regenerates `BETTER_AUTH_SECRET`) or paste the new value; `bun run doctor` names any missing key.",
    "5. `BETTER_AUTH_SECRET` rotation invalidates every session cookie and pending magic link — announce it. `DATABASE_URL` rotation means changing `POSTGRES_PASSWORD` on the `postgres` service; the api/worker reference picks the new value up on redeploy.",
    "",
    "`.gitleaks.toml` (generated from the same contract) makes the pre-commit hook and the CI `secrets` job fail on `NAME=<long value>` for every secret-scoped name; `.env`, `.env.*` (except `.env.example`) are gitignored at every level.",
  ];
  return lines.join("\n");
}

const LOCAL_ONLY_PATH = `The local stack is **self-contained**: a fresh clone needs Bun, Docker and nothing from Railway,
Vercel or any dashboard. Every value in every \`.env.example\` targets the compose Postgres and the
only secret (\`BETTER_AUTH_SECRET\`) is generated on your machine. Proven from a clean clone
(TEACH-26):

\`\`\`sh
git clone <repo> tj && cd tj
find . -name '.env' -o -name '.env.local' | xargs rm -f     # (a clone has none; shown for parity)
bun install --frozen-lockfile
bun run setup --ci        # .env files from the examples, BETTER_AUTH_SECRET generated, Postgres up, migrated
bun run doctor            # every check PASS (WARN only for optional tooling such as gitleaks)
bun run dev               # api :3001, worker :3002, web :5173

# sign in with the console magic link (MAIL_PROVIDER=console prints the link in the api log):
curl -s -X POST localhost:3001/auth/sign-in/magic-link -H 'content-type: application/json' \\
  -H 'origin: http://localhost:5173' \\
  -d '{"email":"teacher@example.test","callbackURL":"http://localhost:5173/"}'
# open the printed http://localhost:3001/auth/magic-link/verify?token=... URL with a cookie jar:
curl -s -c jar '<printed url>' -o /dev/null            # 302 + Set-Cookie tj.session_token
curl -s -b jar localhost:3001/me                        # 200 {"user":{...},"workspaceId":"..."}
curl -s -b jar -X POST localhost:3001/jobs/ping -H 'content-type: application/json' \\
  -H 'origin: http://localhost:5173' -d '{"message":"hello","steps":3}'   # {"jobId":"..."}
curl -N -b jar localhost:3001/jobs/<jobId>/events       # queued -> started -> progress -> completed
\`\`\`

\`bun run setup\` never overwrites an existing \`.env\`; \`bun run doctor\` validates each one against
this contract (missing keys, malformed URLs/ports/enums — values are never printed).`;

const PR_ENVIRONMENTS = `A pull request gets a Vercel preview (\`apps/web\`) and, once Railway billing is active, a Railway
PR environment \`pr-<n>\` that copies \`production\`'s services and variables and gives the api its own
Postgres and domain (\`infra/README.md\` → "PR environments").

- Reference variables (\`DATABASE_URL\`, \`BETTER_AUTH_URL\`) resolve inside the PR environment, so nothing is copied by hand.
- The PR api must accept the preview origin and set a cross-site cookie: \`WEB_ORIGIN_PATTERNS\` (glob of the Vercel preview URLs) and \`COOKIE_SAMESITE=none\` are the two PR-only values in the matrix (\`railway = pr\` / \`both\`).
- The Vercel preview points at the PR api through \`RAILWAY_PR_API_URL_TEMPLATE\` (\`{pr}\` → PR number) resolved by \`scripts/vercel-env.ts\`; \`VITE_API_URL_FALLBACK\` covers branch builds without a PR.
- \`bun run env:check --pr <n>\` compares the names on \`pr-<n>\` against the matrix (\`railway variable list --environment pr-<n>\`).`;

/** The whole `docs/env.md`. */
export function renderEnvDoc(): string {
  return `<!-- GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand. -->

# Environment contract

Single source of truth for every environment variable Teaching Journey reads:
[\`infra/env.contract.ts\`](../infra/env.contract.ts). This page, every \`.env.example\` and
\`.gitleaks.toml\` are generated from it (\`bun run env:generate\`; \`bun run env:generate --check\`
runs in CI and fails on drift). \`bun run doctor\` validates the local \`.env\` files against it and
\`bun run env:check\` compares the variable **names** present on Railway and Vercel with it —
values are never read into logs or docs.

Legend — **Services**: who reads it (\`compose\` = docker compose + root scripts). **Scope**:
\`secret\` values are never printed or committed and have a gitleaks rule. **Local**: the value in
\`.env.example\` (\`—\` = optional, documented commented-out). **Railway** / **Vercel**: which provider
environments carry it (\`prod\`, \`pr\` / \`preview\`, \`both\`, \`n/a\`). **Set by**: see "Where each value
is set".

## Matrix

${renderMatrix()}

## Local-only path

${LOCAL_ONLY_PATH}

## Where each value is set

${bySetBy()}

Expected names per provider target (what \`bun run env:check\` verifies):

${railwaySection()}
${vercelSection()}

Railway post-provisioning checklist (values, never in git; \`infra/railway/provision.sh\` seeds the
\`reference\`/\`template\` ones from this contract via \`scripts/railway-vars.ts\`):

\`\`\`sh
bun scripts/railway-vars.ts api        # NAME=value lines provision.sh passes to \`railway variable set\`
bun scripts/railway-vars.ts worker
bun run env:check                      # names on production vs this matrix; --fix prints the commands
bun run env:check --pr <n> --fix       # same for an open PR environment
\`\`\`

## Rotating a secret

${rotationSection()}

## PR environments

${PR_ENVIRONMENTS}
`;
}

// --- .gitleaks.toml ---------------------------------------------------------------------------------

/** Minimal gitleaks config: defaults + one rule per secret-scoped name. */
export function renderGitleaksConfig(): string {
  const rules = secretNames()
    .map((name) => {
      const id = `tj-${name.toLowerCase().replaceAll("_", "-")}`;
      return `[[rules]]
id = "${id}"
description = "Teaching Journey secret ${name} assigned a literal value (infra/env.contract.ts)"
regex = '''(?i)\\b${name}\\b[ \\t]*[:=][ \\t]*["']?([A-Za-z0-9+/_=.:@-]{20,})["']?'''
keywords = ["${name}"]`;
    })
    .join("\n\n");
  return `# GENERATED from infra/env.contract.ts by \`bun run env:generate\` -- do not edit by hand.
#
# Extends gitleaks' default rules with one rule per secret-scoped variable of the environment
# contract: a literal \`NAME=<20+ chars>\` for any of them fails the pre-commit hook
# (\`gitleaks protect --staged\`) and the CI \`secrets\` job. Examples, docs and tests are allowed to
# show placeholders; the compose credentials (postgres/postgres) are synthetic and allowed.
title = "Teaching Journey"

[extend]
useDefault = true

[allowlist]
description = "Synthetic local values and documentation"
paths = [
  '''\\.env\\.example$''',
  '''^docs/env\\.md$''',
  '''\\.test\\.tsx?$''',
  '''\\.spec\\.ts$''',
]
regexes = [
  '''postgres://postgres:postgres@(localhost|host\\.docker\\.internal|127\\.0\\.0\\.1)''',
  '''\\$\\{\\{[^}]+\\}\\}''',
  '''(process|import\\.meta)\\.env\\.''',
]

${rules}
`;
}

/** Every generated artefact: repo-relative path → content. */
export function renderAll(): Map<string, string> {
  const out = new Map<string, string>();
  for (const file of Object.keys(ENV_FILES) as EnvFile[]) {
    out.set(ENV_FILES[file].path, renderEnvExample(file));
  }
  out.set("docs/env.md", renderEnvDoc());
  out.set(".gitleaks.toml", renderGitleaksConfig());
  return out;
}
