import { randomBytes } from "node:crypto";
import { appendFile, readFile, writeFile } from "node:fs/promises";
import { parseEnv } from "./env";

/** 32 random bytes, base64url (43 chars, no padding) — satisfies better-auth's >= 32 chars. */
export function generateSecret(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Pure: does the dotenv text define `name` with a non-empty value? A commented `# NAME=` or an
 * empty `NAME=` both count as missing (the api's Zod schema treats blanks as unset).
 */
export function hasSecret(envText: string, name: string): boolean {
  const value = parseEnv(envText).get(name);
  return value !== undefined && value.trim() !== "";
}

/** The exact text appended when a secret is generated (a comment + the assignment). */
export function secretBlock(name: string, value: string): string {
  return `\n# Generated by \`bun run setup\` (TEACH-26). Rotating it signs every session out.\n${name}=${value}\n`;
}

/**
 * Pure: the text after filling `name` in. A blank `NAME=` line is completed in place; otherwise
 * `secretBlock` is appended.
 */
export function withSecret(envText: string, name: string, value: string): string {
  const blankLine = new RegExp(`^(\\s*(?:export\\s+)?${name}\\s*=)\\s*$`, "m");
  if (blankLine.test(envText)) return envText.replace(blankLine, `$1${value}`);
  const prefix = envText.length > 0 && !envText.endsWith("\n") ? "\n" : "";
  return `${envText}${prefix}${secretBlock(name, value)}`;
}

/**
 * Writes `NAME=<generated>` into the `.env` at `envPath` when it lacks a non-empty `NAME`.
 * Never logs or returns the value. Returns `"generated"` or `"present"`.
 */
export async function ensureGeneratedSecret(
  envPath: string,
  name: string,
  generate: () => string = generateSecret,
): Promise<"generated" | "present"> {
  const text = await readFile(envPath, "utf8").catch(() => "");
  if (hasSecret(text, name)) return "present";
  const next = withSecret(text, name, generate());
  if (text.length === 0) await appendFile(envPath, next, "utf8");
  else await writeFile(envPath, next, "utf8");
  return "generated";
}
