// The writer's extra Fits rows (#431, `clarity`): writes src/templates/fits-extra.gen.json.
// Usage: bun packages/slides/scripts/fits-extra.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { measureExtraFits } from "../src/templates/fits-extra";

const OUT = join(import.meta.dir, "../src/templates/fits-extra.gen.json");
const out = {
  note: "generated by packages/slides/scripts/fits-extra.ts from capacity.ts (measureTemplate); do not edit",
  stages: measureExtraFits(),
};
writeFileSync(OUT, `${JSON.stringify(out, null, 1)}\n`);
for (const [k, s] of Object.entries(out.stages))
  console.log(
    k,
    Object.entries(s)
      .map(
        ([l, x]) =>
          `${l}(${x.charsPerLine}): ${x.variants.map((v) => `${v.label}=${v.maxCharsPerItem}`).join(", ")}`,
      )
      .join(" | "),
  );
