import { describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { ENV_FILES, secretNames } from "../infra/env.contract";
import { checkOutputs, firstDifference, writeOutputs } from "./env-generate";
import { parseEnvKeys } from "./lib/env";
import {
  commentLines,
  renderAll,
  renderEnvDoc,
  renderEnvExample,
  renderGitleaksConfig,
  renderMatrix,
} from "./lib/env-render";
import { ROOT } from "./lib/paths";

describe("renderEnvExample", () => {
  test("api example: header, required keys uncommented, optional and generated commented", () => {
    const text = renderEnvExample("api");
    expect(text).toStartWith(ENV_FILES.api.header.split("\n")[0] ?? "");
    expect(parseEnvKeys(text)).toEqual([
      "DATABASE_URL",
      "TEST_DATABASE_URL",
      "NODE_ENV",
      "PORT",
      "LOG_LEVEL",
      "WEB_ORIGIN",
      "BETTER_AUTH_URL",
      "MAIL_PROVIDER",
      "ALLOW_WORKSPACE_HEADER_SHIM",
      "AWS_REGION",
      "AI_MODEL_FRONTIER",
      "AI_MODEL_STANDARD",
      "AI_MODEL_SMALL",
    ]);
    expect(text).toContain("\n# BETTER_AUTH_SECRET=\n");
    expect(text).toContain("\n# AWS_BEARER_TOKEN_BEDROCK=\n");
    expect(text).toContain("\n# GOOGLE_CLIENT_SECRET=\n");
    expect(text).toContain("\n# EVENTS_POLL_MS=\n");
    expect(text).toEndWith("\n");
    expect(text).not.toContain("\n\n\n");
  });

  test("worker gets its own PORT and no auth keys", () => {
    const text = renderEnvExample("worker");
    expect(text).toContain("\nPORT=3002\n");
    expect(text).not.toContain("BETTER_AUTH");
  });

  test("root example documents the URLs commented-out and TJ_PG_PORT active", () => {
    const text = renderEnvExample("root");
    expect(parseEnvKeys(text)).toEqual(["TJ_PG_PORT"]);
    expect(text).toContain(
      "# DATABASE_URL=postgres://postgres:postgres@localhost:5432/teaching_journey\n",
    );
  });

  test("commentLines wraps under 100 columns", () => {
    const lines = commentLines("word ".repeat(60));
    for (const line of lines) expect(line.length).toBeLessThanOrEqual(100);
    expect(lines.join(" ").replaceAll("# ", "").trim()).toBe("word ".repeat(60).trim());
  });
});

describe("renderEnvDoc", () => {
  test("has the fixed matrix columns and every required section", () => {
    const doc = renderEnvDoc();
    expect(renderMatrix().split("\n")[0]).toBe(
      "| Variable | Services | Scope | Local (`.env.example`) | Railway | Vercel | Set by | Description |",
    );
    for (const heading of [
      "## Matrix",
      "## Local-only path",
      "## Where each value is set",
      "## Rotating a secret",
      "## PR environments",
    ]) {
      expect(doc).toContain(heading);
    }
    expect(doc).toContain("bun run setup --ci");
    expect(doc).toContain(
      "| `BETTER_AUTH_SECRET` | api | secret | generated by `setup` | both | n/a | generated |",
    );
  });
});

describe("renderGitleaksConfig", () => {
  test("one rule per secret-scoped name, defaults extended", () => {
    const toml = renderGitleaksConfig();
    expect(toml).toContain("useDefault = true");
    for (const name of secretNames()) {
      expect(toml).toContain(`id = "tj-${name.toLowerCase().replaceAll("_", "-")}"`);
      expect(toml).toContain(`keywords = ["${name}"]`);
    }
    expect(toml).toContain("\\.env\\.example$");
  });
});

describe("env:generate", () => {
  test("firstDifference reports the first diverging line", () => {
    expect(firstDifference("a\nb\n", "a\nb\n")).toBeNull();
    expect(firstDifference("a\nb\n", "a\nc\n")).toEqual({
      line: 2,
      expectedLine: "b",
      actualLine: "c",
    });
    expect(firstDifference("a\n", "a\nb\n")).toEqual({
      line: 2,
      expectedLine: "",
      actualLine: "b",
    });
  });

  test("the committed tree is in sync with the contract (run `bun run env:generate` otherwise)", async () => {
    expect(await checkOutputs(ROOT)).toEqual([]);
  });

  test("--check fails on a hand-edited example and write restores it", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "tj-env-generate-"));
    try {
      const first = await writeOutputs(dir);
      expect(first.written.sort()).toEqual([...renderAll().keys()].sort());
      expect(await checkOutputs(dir)).toEqual([]);

      const target = path.join(dir, ENV_FILES.web.path);
      await writeFile(target, `${await readFile(target, "utf8")}VITE_EXTRA=1\n`);
      const drift = await checkOutputs(dir);
      expect(drift.map((d) => d.path)).toEqual([ENV_FILES.web.path]);
      expect(drift[0]?.reason).toBe("differs");

      const second = await writeOutputs(dir);
      expect(second.written).toEqual([ENV_FILES.web.path]);
      expect(await checkOutputs(dir)).toEqual([]);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
